// Public privacy notice. Keep both languages and the generated text/HTML in sync.
export const privacy = {
  en: {
    title: 'Privacy policy', updated: 'Effective 20 September 2026',
    intro: 'This policy explains how DevFridge World processes personal data in the Android app (cool.devfridge.world), the game, TopShelf, and the associated pages at world.devfridge.cool. Wallet addresses and linked activity can be personal data even when no real name is provided.',
    sections: [
      ['controller', '1. Controller and contact', [
        'The controller is Michele Angelo Forlani, an individual based in Italy, publishing as pastaman. For privacy questions and requests, contact welcome@devfridge.cool. This address also handles support. You do not need to connect a wallet or make a payment to contact us.',
        'This notice covers our processing. Wallet providers, blockchains, app stores and external services you choose also have their own responsibilities and privacy policies.'
      ]],
      ['data', '2. Data we process and where it comes from', [
        'From your device and requests: IP address, browser or WebView information, requested URL, timestamps, response and error information. Infrastructure providers receive these technical data when delivering the site, APIs, game assets or APK. Abuse controls use keyed hashes of IP addresses or wallet identifiers; a hash is not a guarantee of anonymity.',
        'From you and your wallet: Solana and, for optional TopShelf registration, EVM public addresses; wallet-connection authorizations; signed messages; selected character, network and payment token; optional display name; and messages or attachments you send to support. We do not ask for recovery phrases or private keys. Wallets perform signing and retain their own keys.',
        'For age checks, the date of birth you enter is sent to the compliance endpoint to check whether you are at least 18. That handler does not save the date of birth; it sets a signed cookie containing the issue time and an adult-status authorization. Self-exclusion records contain the wallet, selected period and start/end times.',
        'For play and score verification: run identifier, selected character, game seed, moves and their timing/sequence, game state, score, replay hash, verification results, temporary signing challenges and signatures. Local history can contain verified scores and the references needed to resume registration.',
        'From public networks: token balances/locks and expiry times, transactions, wallet links, registered scores, seasons, rankings, fees and claims. We query blockchain infrastructure to check access and display or verify TopShelf results.',
        'If you subscribe to the optional newsletter, we process the email address you enter and your subscription choice through Paragraph. Browsing or connecting a wallet does not itself subscribe you. We do not request contacts, camera, microphone or precise device location permissions in the Android app.'
      ]],
      ['purposes', '3. Purposes and legal bases', [
        'Providing the features you request — wallet connection, token-lock access checks, gameplay, verified scores, optional display names, sharing and TopShelf registration — relies on performance of the service relationship or steps you request before it (GDPR Article 6(1)(b)). The necessary wallet and gameplay data are required for those features; without them, access or registration may not work.',
        'Protecting the service, enforcing the adult-only access rule, detecting replayed or invalid scores, limiting abuse and troubleshooting relies on our legitimate interests in security, fair play and reliable operation (Article 6(1)(f)). Self-exclusion implements your request and our legitimate interest in maintaining that restriction. You may object to processing based on legitimate interests.',
        'Optional newsletter delivery relies on consent (Article 6(1)(a)). You can withdraw consent using the unsubscribe link in the email or by writing to us, without affecting earlier lawful processing or your access to the game. Support uses the service basis for service requests and legitimate interests for general enquiries. Handling statutory privacy requests and legally required disclosures relies on applicable legal obligations (Article 6(1)(c)); retaining evidence for an actual dispute relies on the legitimate interest in establishing or defending claims.',
        'We do not sell player data or use the app or Android download pages for targeted advertising. These pages do not add advertising pixels or analytics scripts. Necessary game-state, authorization and security storage is explained below; external sites and the optional newsletter provider have their own practices.'
      ]],
      ['public-data', '4. Public scores, wallet links and sharing', [
        'TopShelf is optional. When you authorize an on-chain registration, the score, relevant wallet addresses and their link, season, transaction and token-transfer information become public on Robinhood Chain. Solana token-lock transactions are also public. Anyone, including explorers and independent indexers, can copy and analyse public chain data. A public display name can be associated with your wallet in the leaderboard.',
        'Public blockchain records are not private or anonymous. The publisher cannot erase a blockchain transaction or unlink addresses already recorded by the contract. Removing a display name or other off-chain record under our control does not remove the chain record or independently retained copies. Do not use a display name containing sensitive information.',
        'Sharing a score is initiated by you in Android’s share chooser. Only the app or recipient you choose receives the shared image/text through that action; their subsequent use is governed by their own practices. We do not publish a score image to a social account automatically.'
      ]],
      ['recipients', '5. Recipients and services', [
        'Hosting and storage providers process data needed to deliver the service: Vercel hosts the website and APIs, and the Redis-compatible KV database stores the temporary game, proof, display-name and protection records described here. The game verification deployment also supports a Fly.io worker; when that worker is enabled, it receives the game request and forwarded IP for verification and abuse prevention.',
        'Blockchain access uses Alchemy and public Solana RPC endpoints (including PublicNode and Solana public endpoints), with Helius supported when configured. The Robinhood Chain RPC service and the wallet you choose handle EVM queries and transactions. A server-side RPC query sends the relevant public addresses/query and the server’s network information; a direct query from your browser or wallet also exposes that client’s network information to the provider.',
        'GitHub distributes the downloadable APK. A browser game can request the Draco model decoder from Google’s gstatic service. These download providers receive ordinary request metadata. Phantom or another wallet you select receives connection/signing requests. The Solana dApp Store or other installation channel processes its own download and review data.',
        'Paragraph handles the optional email subscription. Support and privacy email to welcome@devfridge.cool passes through ImprovMX forwarding and a Google Gmail inbox. These providers receive the email content, addresses, attachments and delivery metadata. Do not send recovery phrases, private keys or unnecessary identity documents.',
        'We may disclose relevant data to competent authorities when legally required, or to advisers where necessary for an actual legal or security matter. The public receives data you deliberately register on-chain or make public in the leaderboard. Optional external links, wallets and sharing destinations are governed by their respective policies.'
      ]],
      ['retention', '6. How long data are kept', [
        'Adult-status cookie: up to one year, or until you clear the relevant browser/WebView data. The birth date is processed for the check and is not saved by the age-check handler.',
        'Server game sessions and mobile registration handoffs: up to six hours from the original run issue time. Signing challenges and temporarily retained native signatures: up to five minutes, never beyond the associated run expiry. Request-limiting counters normally expire after one minute; display-name limits after five minutes; newsletter IP-hash counters after ten minutes. Verification locks expire after two minutes if not released sooner.',
        'Verified score/replay proofs: 90 days from creation. Game activity logs: 90 days after the latest write to that run’s log. In-memory game caches are bounded by capacity and cleared by eviction or process restart; they are not a permanent archive.',
        'Self-exclusion: the selected 24 hours, 7 days or 180 days; the option currently labelled “Permanent” is implemented as ten years. Deleting local data does not cancel it. A request to erase a protection record is assessed individually, including whether a limited record remains necessary to honour the exclusion.',
        'Optional display names have no automatic database expiry. They remain associated with the wallet until replaced, removed following a verified request, or the service is discontinued. Local collection, best scores, saved runs, preferences and wallet authorization persist until cleared, replaced or removed with the app; expiring registration references cease to authorize registration when they expire. A wallet may retain its own connection permission until you revoke it there.',
        'Score-sharing PNGs are stored in app cache. Files older than 24 hours are removed when another image is shared, or when Android clears the cache; there is no daily scheduled cleanup. The last shared file can therefore remain until a later cleanup or manual deletion.',
        'Hosting, delivery, RPC and email providers retain operational/security data under their applicable service settings and policies. Vercel’s published runtime-log windows for Pro are one day, or up to 30 days with extended observability; these windows do not describe every provider’s security logs or backups. We do not promise that clearing app data deletes provider logs. Any copies kept to investigate an incident or dispute are limited to what is necessary for that purpose and applicable obligations.',
        'Newsletter data are kept while subscribed; after unsubscribing, delivery stops and limited suppression/consent records may remain to respect that choice. Support correspondence is kept as needed to resolve and follow up the enquiry and to document its outcome or an applicable legal obligation/dispute; you may request earlier deletion. Public chain records and independently copied data can remain indefinitely.'
      ]],
      ['transfers', '7. International processing', [
        'The controller is in Italy, but hosting, database, RPC, download, newsletter and email services can process data outside the European Economic Area, including in the United States. Blockchain nodes and public readers are distributed globally. This service does not promise that all data stay in Italy or the EU.',
        'For provider transfers subject to GDPR, the relevant service arrangement must provide a lawful transfer mechanism, such as an applicable adequacy decision or Standard Contractual Clauses and any necessary supplementary measures. Vercel’s Pro data-processing addendum includes the EU Standard Contractual Clauses; Google describes its applicable transfer frameworks in the link below. Those arrangements do not make a public blockchain private or cover every independent recipient. Contact us for information about the provider and safeguards applicable to your data, or a copy where available.'
      ]],
      ['rights', '8. Your rights and how to request deletion', [
        'Subject to applicable conditions, you can request access, correction, erasure, restriction and data portability; object to processing based on legitimate interests; and withdraw newsletter consent. You may complain to the Italian Garante per la protezione dei dati personali or the competent supervisory authority where you live or work. Using the service does not waive these rights.',
        'Email welcome@devfridge.cool with the subject “Privacy request” or “Delete my DevFridge data”. Specify the request, the public wallet address(es) or newsletter email concerned, and any run identifiers you know. No payment or token purchase is required. We will request only proportionate evidence of control when necessary, such as a fresh non-transaction wallet signature or verification through the subscribed email. Never send your recovery phrase or private key.',
        'A deletion request can cover your off-chain display name, support records and other identifiable service records under our control, subject to justified retention exceptions. We explain any data we must retain, why and for how long or by what criterion. Blockchain records cannot be erased by us. We respond without undue delay, normally within one month; if a lawful extension is necessary because of complexity or volume, we explain it within that first month.',
        'To clear device data, use Android Settings → Apps → DevFridge World → Storage: clear cache for temporary files or clear storage for local settings/history and WebView data. Uninstalling removes app-local data. Revoke wallet permissions in the wallet, and clear Phantom’s website data for browser-side registration copies. These actions do not submit a server deletion request or cancel a self-exclusion. A wallet-connected profile can be closed by requesting deletion of the associated off-chain data by email.'
      ]],
      ['children-security', '9. Age restrictions, security and automated checks', [
        'The game is intended for people aged 18 or over. If you believe a minor has supplied personal data, contact us so we can investigate and address it, including deletion where appropriate. Do not submit another person’s information unnecessarily.',
        'We use HTTPS, wallet signatures, expiring authorizations and access controls to protect the service. The Android app requests internet access and vibration, does not take custody of wallet keys and disables its own Android backup. No system can guarantee absolute security.',
        'Automated rules check age status, token locks, exclusions, signatures, timing and score consistency. A failed check can block access or score registration. You can request an explanation and human review through the support address. We do not use these records to build advertising profiles.'
      ]],
      ['changes', '10. Changes to this notice', [
        'We update the effective date when this notice changes and provide an appropriate notice of material changes; where a new use requires consent, we request it separately. This online policy supersedes earlier preliminary Android privacy notices for the processing described here. Older installed APKs can still contain an earlier offline technical notice; this page is the current policy.'
      ]],
    ],
    linksTitle: 'Provider information and privacy rights',
  },
  it: {
    title: 'Informativa sulla privacy', updated: 'In vigore dal 20 settembre 2026',
    intro: 'Questa informativa descrive il trattamento dei dati personali nell’app Android DevFridge World (cool.devfridge.world), nel gioco, in TopShelf e nelle relative pagine di world.devfridge.cool. Gli indirizzi dei wallet e le attività collegate possono essere dati personali anche senza un nome reale.',
    sections: [
      ['controller', '1. Titolare e contatti', [
        'Il titolare del trattamento è Michele Angelo Forlani, persona fisica con sede in Italia, che pubblica con il nome pastaman. Per domande e richieste sulla privacy scrivi a welcome@devfridge.cool, utilizzato anche per l’assistenza. Non occorre collegare un wallet o effettuare un pagamento per contattarci.',
        'L’informativa riguarda i trattamenti svolti da noi. Fornitori dei wallet, blockchain, app store e servizi esterni scelti dall’utente hanno anche proprie responsabilità e informative.'
      ]],
      ['data', '2. Dati trattati e provenienza', [
        'Dal dispositivo e dalle richieste: indirizzo IP, informazioni sul browser o WebView, URL richiesto, orari, informazioni sulle risposte e sugli errori. I fornitori dell’infrastruttura ricevono questi dati tecnici per distribuire sito, API, risorse del gioco o APK. I controlli contro gli abusi usano hash con chiave di indirizzi IP o identificativi wallet: un hash non garantisce l’anonimato.',
        'Da te e dal wallet: indirizzi pubblici Solana e, per la registrazione facoltativa TopShelf, EVM; autorizzazioni alla connessione; messaggi firmati; personaggio, rete e token di pagamento scelti; eventuale nome pubblico; messaggi e allegati inviati all’assistenza. Non chiediamo frasi di recupero o chiavi private. Le firme vengono eseguite dal wallet, che conserva le proprie chiavi.',
        'Per la verifica dell’età, la data di nascita inserita viene inviata al servizio di verifica per controllare il compimento dei 18 anni. Il relativo gestore non salva la data: imposta un cookie firmato con l’istante di emissione e un’autorizzazione che attesta la maggiore età. L’autoesclusione registra wallet, periodo selezionato e date di inizio e fine.',
        'Per gioco e verifica del punteggio: identificativo della partita, personaggio, seme di gioco, mosse con tempi e sequenza, stato della partita, punteggio, hash del replay, risultati delle verifiche, richieste temporanee di firma e firme. La cronologia locale può contenere punteggi verificati e riferimenti per riprendere la registrazione.',
        'Dalle reti pubbliche: saldi e blocchi dei token con scadenze, transazioni, collegamenti fra wallet, punteggi registrati, stagioni, classifiche, commissioni e claim. Interroghiamo l’infrastruttura blockchain per verificare l’accesso e visualizzare o verificare i risultati TopShelf.',
        'Se ti iscrivi alla newsletter facoltativa, trattiamo tramite Paragraph l’indirizzo email inserito e la scelta di iscrizione. Visitare il sito o collegare un wallet non comporta l’iscrizione. L’app Android non richiede permessi per contatti, fotocamera, microfono o posizione precisa del dispositivo.'
      ]],
      ['purposes', '3. Finalità e basi giuridiche', [
        'Le funzioni richieste — connessione wallet, verifica dei token bloccati, gioco, punteggi verificati, nome pubblico facoltativo, condivisione e registrazione TopShelf — si basano sull’esecuzione del rapporto di servizio o di misure richieste prima di esso (art. 6, par. 1, lett. b del GDPR). I dati necessari del wallet e della partita sono richiesti per queste funzioni: senza di essi accesso o registrazione potrebbero non funzionare.',
        'Protezione del servizio, applicazione del limite di età, rilevamento di punteggi non validi o riutilizzati, contrasto agli abusi e diagnosi dei problemi si basano sul legittimo interesse alla sicurezza, alla correttezza del gioco e all’affidabilità del servizio (lett. f). L’autoesclusione attua la tua richiesta e il nostro legittimo interesse a mantenerla. Puoi opporti ai trattamenti fondati sul legittimo interesse.',
        'La newsletter facoltativa si basa sul consenso (lett. a). Puoi revocarlo dal collegamento di disiscrizione nelle email o scrivendoci, senza pregiudicare i trattamenti precedenti o l’accesso al gioco. L’assistenza si basa sul rapporto di servizio per le relative richieste e sul legittimo interesse per le domande generali. Gestire le richieste privacy e le comunicazioni imposte dalla legge si basa sugli obblighi legali applicabili (lett. c); conservare prove per una controversia effettiva si basa sul legittimo interesse ad accertare o difendere diritti.',
        'Non vendiamo i dati dei giocatori e non utilizziamo l’app o le pagine di download Android per pubblicità mirata. Queste pagine non aggiungono pixel pubblicitari o script di analytics. La memorizzazione necessaria per gioco, autorizzazioni e sicurezza è descritta di seguito; siti esterni e fornitore della newsletter hanno proprie pratiche.'
      ]],
      ['public-data', '4. Punteggi pubblici, collegamenti dei wallet e condivisione', [
        'TopShelf è facoltativo. Autorizzando una registrazione sulla blockchain, punteggio, relativi indirizzi wallet e loro collegamento, stagione, transazione e trasferimenti di token diventano pubblici su Robinhood Chain. Anche le transazioni di blocco dei token su Solana sono pubbliche. Chiunque, inclusi explorer e indicizzatori indipendenti, può copiare e analizzare questi dati. Un nome pubblico può essere associato al wallet nella classifica.',
        'I dati pubblici della blockchain non sono riservati o anonimi. Il publisher non può cancellare una transazione o scollegare indirizzi già registrati dal contratto. Rimuovere un nome pubblico o altri dati fuori dalla blockchain sotto il nostro controllo non cancella le registrazioni on-chain o le copie conservate autonomamente da terzi. Non inserire informazioni sensibili nel nome pubblico.',
        'La condivisione del punteggio viene avviata da te tramite il selettore Android. Solo l’app o il destinatario scelto riceve immagine/testo attraverso quell’azione; il successivo utilizzo dipende dalle sue pratiche. Non pubblichiamo automaticamente immagini del punteggio sui tuoi account social.'
      ]],
      ['recipients', '5. Destinatari e servizi', [
        'I fornitori di hosting e archiviazione trattano i dati necessari al servizio: Vercel ospita sito e API, mentre il database KV compatibile con Redis conserva i dati temporanei di gioco, prove, nomi pubblici e protezione descritti qui. Il sistema di verifica supporta anche un worker Fly.io: quando abilitato, riceve richiesta di gioco e IP inoltrato per verifica e contrasto agli abusi.',
        'L’accesso alla blockchain usa Alchemy ed endpoint RPC pubblici Solana, inclusi PublicNode e gli endpoint pubblici Solana; Helius è supportato quando configurato. Il servizio RPC di Robinhood Chain e il wallet scelto gestiscono interrogazioni e transazioni EVM. Una richiesta RPC dal server trasmette indirizzi pubblici/interrogazione e dati di rete del server; una richiesta diretta dal browser o dal wallet espone al fornitore anche i dati di rete di quel client.',
        'GitHub distribuisce l’APK scaricabile. Il gioco nel browser può richiedere il decoder dei modelli Draco al servizio gstatic di Google. Questi fornitori ricevono i normali metadati delle richieste. Phantom o un altro wallet scelto riceve le richieste di connessione e firma. Il Solana dApp Store o un altro canale di installazione tratta autonomamente i propri dati di download e recensione.',
        'Paragraph gestisce l’iscrizione email facoltativa. Le email di assistenza e privacy a welcome@devfridge.cool transitano attraverso l’inoltro ImprovMX e una casella Google Gmail. Questi fornitori ricevono contenuto, indirizzi, allegati e metadati di consegna. Non inviare frasi di recupero, chiavi private o documenti identificativi non necessari.',
        'Possiamo comunicare dati pertinenti alle autorità competenti quando richiesto dalla legge o a consulenti quando necessario per una questione legale o di sicurezza effettiva. Il pubblico riceve i dati che scegli di registrare sulla blockchain o rendere pubblici in classifica. Collegamenti esterni, wallet e destinazioni di condivisione facoltativi sono soggetti alle rispettive informative.'
      ]],
      ['retention', '6. Tempi di conservazione', [
        'Cookie di maggiore età: fino a un anno o fino alla cancellazione dei dati del browser/WebView interessato. La data di nascita è trattata per il controllo e non viene salvata dal gestore della verifica dell’età.',
        'Sessioni di gioco sul server e riferimenti per la registrazione mobile: fino a sei ore dall’emissione originale della partita. Richieste di firma e firme native conservate temporaneamente: fino a cinque minuti, mai oltre la scadenza della partita associata. I contatori contro gli abusi scadono normalmente dopo un minuto; quelli per i nomi pubblici dopo cinque minuti; gli hash IP della newsletter dopo dieci minuti. I blocchi tecnici della verifica scadono dopo due minuti, se non rilasciati prima.',
        'Prove di verifica dei punteggi/replay: 90 giorni dalla creazione. Log delle attività di gioco: 90 giorni dall’ultima scrittura nel log della partita. Le cache di gioco in memoria hanno capacità limitata e vengono svuotate per sostituzione o riavvio del processo; non sono un archivio permanente.',
        'Autoesclusione: le 24 ore, i 7 giorni o i 180 giorni scelti; l’opzione attualmente chiamata “Permanente” è implementata come dieci anni. Cancellare i dati locali non la annulla. Una richiesta di cancellazione di un dato di protezione viene valutata singolarmente, inclusa l’eventuale necessità di conservarne una parte per rispettare l’esclusione.',
        'I nomi pubblici facoltativi non hanno una scadenza automatica nel database. Restano associati al wallet fino alla sostituzione, rimozione a seguito di richiesta verificata o cessazione del servizio. Collezione, record, partite salvate, preferenze e autorizzazione wallet locali restano fino alla cancellazione, sostituzione o rimozione dell’app; i riferimenti di registrazione non consentono più la registrazione dopo la loro scadenza. Il wallet può mantenere un proprio permesso di connessione fino alla revoca al suo interno.',
        'Le immagini PNG condivise sono nella cache dell’app. I file più vecchi di 24 ore vengono rimossi quando si condivide un’altra immagine o quando Android svuota la cache; non esiste una pulizia giornaliera programmata. L’ultimo file condiviso può quindi restare fino a una pulizia successiva o manuale.',
        'Fornitori di hosting, distribuzione, RPC ed email conservano dati operativi e di sicurezza secondo le rispettive impostazioni e informative. Le finestre pubblicate da Vercel per i log runtime Pro sono un giorno o fino a 30 giorni con osservabilità estesa; non descrivono tutti i log di sicurezza o i backup di ogni fornitore. Svuotare l’app non garantisce la cancellazione dei log dei fornitori. Eventuali copie necessarie a indagare un incidente o una controversia sono limitate a quanto necessario per quella finalità e per gli obblighi applicabili.',
        'I dati newsletter sono conservati durante l’iscrizione; dopo la disiscrizione l’invio cessa, mentre possono restare dati limitati di esclusione dagli invii/prova del consenso per rispettare la scelta. La corrispondenza di assistenza è conservata per risolvere e seguire la richiesta, documentarne l’esito o gestire un obbligo legale/controversia applicabile; puoi chiederne prima la cancellazione. Registrazioni blockchain e copie indipendenti possono restare a tempo indeterminato.'
      ]],
      ['transfers', '7. Trattamento internazionale', [
        'Il titolare è in Italia, ma servizi di hosting, database, RPC, download, newsletter ed email possono trattare dati fuori dallo Spazio economico europeo, inclusi gli Stati Uniti. Nodi blockchain e lettori dei dati pubblici sono distribuiti nel mondo. Il servizio non garantisce che tutti i dati restino in Italia o nell’UE.',
        'Per i trasferimenti dei fornitori soggetti al GDPR, il relativo rapporto deve prevedere un meccanismo lecito, come una decisione di adeguatezza applicabile oppure Clausole contrattuali standard e le eventuali misure supplementari necessarie. L’accordo Vercel Pro sul trattamento dei dati include le Clausole contrattuali standard UE; Google descrive i propri meccanismi di trasferimento nel collegamento sotto. Questi strumenti non rendono privata una blockchain pubblica né coprono ogni destinatario indipendente. Puoi contattarci per informazioni sul fornitore e sulle garanzie applicabili ai tuoi dati o per ottenerne copia, ove disponibile.'
      ]],
      ['rights', '8. Diritti e richiesta di cancellazione', [
        'Alle condizioni applicabili puoi chiedere accesso, rettifica, cancellazione, limitazione e portabilità dei dati; opporti al trattamento basato sul legittimo interesse; revocare il consenso alla newsletter. Puoi presentare reclamo al Garante per la protezione dei dati personali o all’autorità competente del luogo di residenza o lavoro. Utilizzare il servizio non comporta la rinuncia a questi diritti.',
        'Scrivi a welcome@devfridge.cool con oggetto “Richiesta privacy” o “Cancella i miei dati DevFridge”. Indica la richiesta, gli indirizzi pubblici dei wallet o l’email di iscrizione interessati e gli eventuali identificativi delle partite conosciuti. Non occorrono pagamenti o acquisti di token. Chiederemo solo una prova proporzionata del controllo, se necessaria, come una nuova firma di messaggio senza transazione o una verifica tramite l’email iscritta. Non inviare mai frase di recupero o chiave privata.',
        'La richiesta può riguardare nome pubblico fuori dalla blockchain, corrispondenza di assistenza e altri dati identificabili del servizio sotto il nostro controllo, salvo eccezioni di conservazione giustificate. Spiegheremo quali dati dobbiamo mantenere, perché e per quanto tempo o secondo quale criterio. Non possiamo cancellare i dati blockchain. Rispondiamo senza ingiustificato ritardo, normalmente entro un mese; se complessità o numero delle richieste rendono necessaria una proroga consentita, la motiviamo entro il primo mese.',
        'Per cancellare i dati del dispositivo usa Impostazioni Android → App → DevFridge World → Archiviazione: svuota la cache per i file temporanei o cancella lo spazio di archiviazione per impostazioni, cronologia e dati WebView locali. La disinstallazione rimuove i dati locali dell’app. Revoca i permessi nel wallet e cancella i dati del sito in Phantom per le copie di registrazione nel browser. Queste azioni non inviano una richiesta di cancellazione al server e non annullano l’autoesclusione. Puoi chiudere il profilo collegato al wallet chiedendo via email la cancellazione dei relativi dati fuori dalla blockchain.'
      ]],
      ['children-security', '9. Età, sicurezza e controlli automatici', [
        'Il gioco è destinato a persone di almeno 18 anni. Se ritieni che un minore abbia fornito dati personali, contattaci per consentirci di verificare e intervenire, anche cancellando i dati quando appropriato. Non inviare inutilmente dati di altre persone.',
        'Usiamo HTTPS, firme wallet, autorizzazioni a scadenza e controlli di accesso per proteggere il servizio. L’app Android richiede accesso a internet e vibrazione, non custodisce le chiavi dei wallet e disabilita il proprio backup Android. Nessun sistema garantisce sicurezza assoluta.',
        'Regole automatiche verificano maggiore età, token bloccati, esclusioni, firme, tempi e coerenza dei punteggi. Un controllo negativo può impedire accesso o registrazione del punteggio. Puoi chiedere spiegazioni e una revisione umana all’indirizzo di assistenza. Non usiamo questi dati per creare profili pubblicitari.'
      ]],
      ['changes', '10. Modifiche all’informativa', [
        'Aggiorniamo la data di efficacia quando l’informativa cambia e comunichiamo adeguatamente le modifiche sostanziali; quando un nuovo utilizzo richiede consenso, lo chiediamo separatamente. Questa informativa online sostituisce le precedenti informative preliminari Android per i trattamenti qui descritti. Gli APK già installati possono contenere una precedente nota tecnica offline: questa pagina è l’informativa aggiornata.'
      ]],
    ],
    linksTitle: 'Informazioni sui fornitori e diritti privacy',
  },
};

export const privacyLinks = [
  ['Vercel', 'https://vercel.com/legal/privacy-notice'],
  ['Vercel DPA', 'https://vercel.com/legal/dpa'],
  ['Vercel runtime logs', 'https://vercel.com/docs/logs/runtime'],
  ['Fly.io', 'https://www.fly.io/legal/privacy-policy/'],
  ['GitHub', 'https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement'],
  ['Google', 'https://policies.google.com/privacy'],
  ['Google — transfers', 'https://policies.google.com/privacy/frameworks'],
  ['Paragraph', 'https://paragraph.com/privacy'],
  ['ImprovMX', 'https://improvmx.com/transparency/privacy-policy/'],
  ['Garante per la protezione dei dati personali', 'https://www.garanteprivacy.it/'],
];
