import { makePitch, pitchHTML, pitchMarkdown } from './pitch.mjs';
export const ORIGIN = 'https://synapse.devfridge.cool';
export const PASTA = '39kMeX4HVRW9qbbiHSPbRQ9xeXUF18GrNP6gL61Ppump';
export const PROGRAM = '9RY54dNPYTzDyh3TfFqDdt2b2KMM56KW1tw9erRTGQo6';
export const SNAPSHOT_URL = 'https://raw.githubusercontent.com/mikeminer/devfridge/master/knowledge/data/snapshot.json';
const KNOWLEDGE = 'https://github.com/mikeminer/devfridge/tree/master/knowledge';
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const finite = value => value !== null && value !== undefined && value !== '' && Number.isFinite(Number(value)) && Number(value) >= 0;
const usd = value => finite(value) ? new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: Number(value) < .01 && Number(value) > 0 ? 10 : 2 }).format(Number(value)) : 'Not observed';
const safeURL = value => { try { const u = new URL(value); return u.protocol === 'https:' ? u.href : '#'; } catch { return '#'; } };

export function observation(record = {}, now = Date.now()) {
  const age = now - Date.parse(record.fetched_at);
  return { ...record, status: !record.data ? 'unavailable' : record.status !== 'ok' || !Number.isFinite(age) || age > 36 * 3600000 || age < -300000 ? 'stale' : 'ok' };
}

export function exactSupply(data = {}) {
  if (!/^\d+$/.test(data.supply_base_units ?? '') || !Number.isInteger(data.decimals) || data.decimals < 0 || data.decimals > 36) return null;
  const digits = data.supply_base_units.padStart(data.decimals + 1, '0');
  return data.decimals ? `${digits.slice(0, -data.decimals)}.${digits.slice(-data.decimals)}`.replace(/\.?0+$/, '') : digits;
}

export function buildBrief(snapshot, { now = Date.now(), fallback = false } = {}) {
  if (snapshot.schema_version !== 1 || !Number.isFinite(Date.parse(snapshot.attempted_at)) || !Array.isArray(snapshot.registry?.data) || !snapshot.assets) throw new Error('Invalid knowledge snapshot');
  const assets = snapshot.registry.data.map(asset => {
    if (!['solana', 'robinhood'].includes(asset.chain) || !(asset.chain === 'solana' ? /^[1-9A-HJ-NP-Za-km-z]{32,44}$/ : /^0x[0-9a-fA-F]{40}$/).test(asset.address) || asset.id !== asset.chain + ':' + (asset.chain === 'robinhood' ? asset.address.toLowerCase() : asset.address)) throw new Error('Invalid asset identity');
    const state = snapshot.assets[asset.id] ?? {};
    const chain = observation(state.chain, now), market = observation(state.market, now);
    const pairs = (market.data?.pairs ?? []).filter(p => finite(p.liquidity?.usd)).sort((a, b) => Number(b.liquidity.usd) - Number(a.liquidity.usd));
    const slug = asset.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    return { ...asset, chain_observation: chain, market_observation: market, total_supply: exactSupply(chain.data), largest_indexed_pool: pairs[0] ?? null,
      lock_coverage: { status: 'not_collected', source: 'https://scan.devfridge.cool', note: 'Per-token locked percentage and unlock schedule are not collected in this snapshot. Verify the full mint in Scan.' },
      explorer: (asset.chain === 'solana' ? 'https://solscan.io/token/' : 'https://robinhoodchain.blockscout.com/token/') + asset.address,
      market_link: (asset.chain === 'solana' ? 'https://pump.fun/coin/' : 'https://www.ponsfamily.com/launchpad/') + asset.address,
      graph: `${ORIGIN}/graph.html#/${encodeURIComponent(`assets/${asset.chain}/${slug}-${asset.address.slice(0, 8).toLowerCase()}.md`)}` };
  }).sort((a, b) => a.address === PASTA ? -1 : b.address === PASTA ? 1 : a.name.localeCompare(b.name));
  if (!assets.some(a => a.chain === 'solana' && a.address === PASTA) || new Set(assets.map(a => a.id)).size !== assets.length) throw new Error('Missing canonical mint or duplicate asset');
  const documents = Object.entries(snapshot.documents ?? {}).filter(([url]) => /^https:\/\/docs\.devfridge\.cool(?:\/[a-z0-9-]*)?$/.test(url)).map(([url, record]) => ({ url, title: record.data?.title ?? url, ...observation({ status: record.status, fetched_at: record.fetched_at, data: record.data ? { available: true } : null }, now) }));
  const protocol = Object.fromEntries(['activity', 'lp', 'reported_stats'].map(key => [key, observation(snapshot.protocol?.[key], now)]));
  return { protocol, pitch: makePitch(protocol), schema_version: 1, title: 'DevFridge Synapse — product evidence & community pilots', canonical_url: ORIGIN + '/', canonical_pasta_mint: PASTA, solana_program: PROGRAM,
    snapshot_attempted_at: snapshot.attempted_at, fallback, registry: observation(snapshot.registry, now), assets, documents,
    contacts: { connect: observation(snapshot.contacts?.connect, now), team: verifiedTeam(snapshot.contacts?.team, now) },
    scope: 'Official DevFridge ecosystem assets on Solana and Robinhood Chain. Address and network identify each asset; ticker alone does not.',
    economics: 'Mainnet claims charge 2%: a PASTA lock burns that fee directly; other supported mints use a Jupiter buyback into PASTA and burn. Get Featured costs 0.1 SOL / 24h, 0.18 SOL / 48h or 0.5 SOL / 7d, plus network fees; payments fund a separate PumpSwap buy/burn crank. These mechanics are not measured revenue, holder distributions or a price floor.',
    limits: ['Daily observations, not real-time quotes. Pool liquidity is a provider estimate, not executable depth. PASTA LP mint supply is observed separately.', 'Pump.fun bonding-curve progress, executable slippage, Solana holder clusters, LP ownership and upcoming unlocks are not collected here.', 'A token lock does not prove liquidity is locked. No cross-network redemption relationship is assumed.', 'Not affiliated with any other token using the PASTA ticker.'],
    sources: { snapshot: SNAPSHOT_URL, knowledge: KNOWLEDGE, freshness: KNOWLEDGE + '/operations/freshness.md', official: 'https://connect.devfridge.cool', program: 'https://docs.devfridge.cool/program', tokenomics: 'https://docs.devfridge.cool/tokenomics' } };
}

const statusText = record => `${record.status === 'ok' ? 'Observed' : record.status === 'stale' ? 'STALE' : 'Unavailable'} · ${record.fetched_at ?? 'no successful observation'}`;
const authority = (data, key) => !data || !(key in data) ? 'Not observed' : data[key] === null ? 'None at observation' : data[key];

function verifiedTeam(record, now) {
  const result = observation(record, now);
  if (!result.data) return result;
  return { ...result, data: { ...result.data, members: (result.data.members ?? []).filter(member => {
    const proof = member.commitment, age = now - Date.parse(proof?.checked_at);
    return result.status === 'ok' && proof?.status === 'verified' && proof.mint === PASTA && Number.isFinite(age) && age >= 0 && age <= 36*3600000 && proof.valid_until * 1000 > now;
  }) } };
}

function contactSection(brief) {
  const { connect, team } = brief.contacts;
  return `<section id="contacts"><div class="section-heading"><h2>Official contacts & team</h2><a href="/graph.html#/contacts/index.md">Explore contact notes ↗</a></div><p>Published by Connect and the Team roster. Only team members with verified PASTA commitment are included. Verification uses the Team tier amounts and lock durations; it does not verify real-world identity.</p><h3>Project leader, communities & updates</h3><p class="timestamp">Connect: ${escape(statusText(connect))}</p><div class="doc-links">${(connect.data?.entries ?? []).map(c => `<a href="${escape(safeURL(c.url))}">${escape(c.label)}<small>${escape(c.group)}</small></a>`).join('') || '<p>Contact details unavailable. Check Connect.</p>'}</div><h3>Team with verified commitment</h3><p class="timestamp">Team roster: ${escape(statusText(team))} · <a href="https://team.devfridge.cool/">Team site</a></p><div class="assets">${(team.data?.members ?? []).map(m => `<article class="asset"><h3>${escape(m.name)}</h3><p>${escape(m.role)} · Verified commitment</p><p class="timestamp">Checked: ${escape(m.commitment.checked_at)}</p><code class="mint">${escape(m.wallet)}</code><ul>${m.contacts.map(c => `<li>${c.url ? `<a href="${escape(safeURL(c.url))}">${escape(c.platform)}: ${escape(c.handle)}</a>` : `${escape(c.platform)}: ${escape(c.handle)}`}</li>`).join('')}</ul></article>`).join('') || '<p>Team details unavailable. Check the team site.</p>'}</div></section>`;
}

function assetCard(asset) {
  const chain = asset.chain_observation, market = asset.market_observation, pair = asset.largest_indexed_pool;
  const solana = asset.chain === 'solana';
  return `<article class="asset" id="asset-${escape(asset.address)}"><header><div><span class="network">${solana ? 'SOLANA' : 'ROBINHOOD CHAIN · 4663'}</span><h3>${escape(asset.name)} <span>$${escape(asset.symbol)}</span></h3></div><a href="${escape(asset.graph)}">Research ↗</a></header>
<code class="mint">${escape(asset.address)}</code><div class="asset-metrics">${solana ? `<div><span>Largest indexed pool</span><strong>${usd(pair?.liquidity?.usd)}</strong></div><div><span>Pool volume · 24h</span><strong>${usd(pair?.volume?.h24)}</strong></div>` : `<div><span>Holder accounts</span><strong>${escape(market.data?.holders_count ?? 'Not observed')}</strong></div><div><span>Market depth</span><strong>Not collected</strong></div>`}</div>
<p class="timestamp">Market: ${escape(statusText(market))}</p><details><summary>Supply, controls & sources</summary><dl><dt>Total supply</dt><dd>${escape(asset.total_supply ?? 'Not observed')}</dd>${solana ? `<dt>Token-2022</dt><dd>${chain.data ? escape(chain.data.token_2022 === true ? 'Yes' : 'No') : 'Not observed'}</dd><dt>Mint authority</dt><dd>${escape(authority(chain.data, 'mint_authority'))}</dd><dt>Freeze authority</dt><dd>${escape(authority(chain.data, 'freeze_authority'))}</dd>` : '<dt>Admin / proxy controls</dt><dd>Not established by supply reads</dd>'}<dt>Locked % / unlocks</dt><dd>Not collected — verify in Scan</dd>${solana ? `<dt>Pool price / FDV</dt><dd>${usd(pair?.priceUsd)} / ${usd(pair?.fdv)}</dd><dt>Indexed pool</dt><dd>${escape(pair?.pairAddress ?? 'Not observed')}</dd>` : ''}</dl><p class="timestamp">Chain: ${escape(statusText(chain))}</p><p><a href="${escape(asset.explorer)}">On-chain explorer</a> · <a href="${escape(safeURL(market.source))}">Market source</a> · <a href="${escape(asset.graph)}">Full note & extensions</a></p></details><footer><a href="${escape(asset.market_link)}">${solana ? 'View on Pump.fun' : 'View on Pons'} ↗</a><button data-copy="${escape(asset.address)}" aria-label="Copy ${escape(asset.name)} address">Copy address</button></footer></article>`;
}

export function renderHTML(brief) {
  const pasta = brief.assets.find(a => a.address === PASTA), pool = pasta.largest_indexed_pool;
  const description = `DevFridge for KOLs and builders: explore the timelock, scanner and SDK, verify adoption and PASTA LP evidence, and discuss a community pilot. Canonical PASTA: ${PASTA}.`;
  const schema = JSON.stringify({ '@context': 'https://schema.org', '@type': 'WebPage', name: brief.title, url: brief.canonical_url, description, dateModified: brief.snapshot_attempted_at, about: { '@type': 'Thing', name: 'DevFridge PASTA on Solana', identifier: PASTA }, hasPart: [{ '@type': 'DigitalDocument', name: 'Investor brief as Markdown', url: ORIGIN + '/brief.md' }, { '@type': 'Dataset', name: 'Investor brief as JSON', url: ORIGIN + '/brief.json' }] }).replace(/</g, '\\u003c');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Synapse | DevFridge product evidence & community pilots</title><meta name="description" content="${escape(description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${ORIGIN}/"><meta property="og:type" content="website"><meta property="og:title" content="DevFridge Synapse · A lock your community can use."><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${ORIGIN}/"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="DevFridge Synapse · Product evidence & community pilots"><meta name="twitter:description" content="${escape(description)}"><link rel="alternate" type="text/markdown" href="${ORIGIN}/brief.md" title="Concise investor brief"><link rel="alternate" type="application/json" href="${ORIGIN}/brief.json" title="Structured investor evidence"><link rel="stylesheet" href="/brief.css"><script type="application/ld+json">${schema}</script><script src="/brief-ui.js" defer></script></head>
<body><a class="skip" href="#brief">Skip to investor brief</a><header class="site-header"><a class="wordmark" href="/">SYNAPSE <span>by DevFridge</span></a><nav aria-label="Primary"><a href="#products">Products</a><a href="#adoption">Evidence</a><a href="#pilot">SDK pilot</a><a href="#solana">Assets</a><a href="https://ir.devfridge.cool">Ask IR ↗</a><a href="/graph.html">Open graph ↗</a><a href="https://connect.devfridge.cool">Official links ↗</a></nav></header>
<main id="brief"><section class="intro"><div><p class="eyebrow">DEVFRIDGE · FOR BUILDERS & COMMUNITY LEADERS</p><h1>A lock your<br>community can use.</h1><p class="lead">Turn token commitment into access, public proof and reusable integrations. Explore the working products, check the adoption evidence and discuss an SDK pilot.</p><div class="actions"><a href="https://sdk.devfridge.cool">Explore the SDK ↗</a><a href="#contacts">Discuss a community pilot</a><a href="/graph.html">Explore the knowledge graph</a></div></div><aside class="identity"><span class="eyebrow">CANONICAL $PASTA · SOLANA</span><code class="mint">${PASTA}</code><p>Ticker ≠ identity. Other PASTA tokens are unrelated.</p><div class="actions"><button data-copy="${PASTA}">Copy mint</button><a href="${pasta.explorer}">Verify on-chain ↗</a></div></aside></section>
<div class="freshness${brief.fallback || brief.registry.status !== 'ok' ? ' warning' : ''}"><strong>${brief.fallback ? 'Saved fallback · live feed unavailable' : brief.registry.status === 'stale' ? 'Older evidence — check source dates' : 'Daily evidence snapshot'}</strong><time datetime="${escape(brief.snapshot_attempted_at)}">${escape(brief.snapshot_attempted_at)}</time><a href="${brief.sources.freshness}">Source status & discrepancies ↗</a></div>
${pitchHTML(brief)}
<section class="quick-stats" aria-label="PASTA observations"><div><span>PASTA · largest indexed pool</span><strong>${usd(pool?.liquidity?.usd)}</strong><small>${escape(statusText(pasta.market_observation))}</small></div><div><span>PASTA · pool volume / 24h</span><strong>${usd(pool?.volume?.h24)}</strong><small>Same pool · DexScreener observation</small></div><div><span>PASTA · mint / freeze authority</span><strong>${pasta.chain_observation.data?.mint_authority === null && pasta.chain_observation.data?.freeze_authority === null ? 'Both absent' : 'Review controls'}</strong><small>${escape(statusText(pasta.chain_observation))}</small></div><div><span>PASTA · locked % / next unlock</span><strong>Not collected</strong><small><a href="https://scan.devfridge.cool">Verify the full mint in Scan ↗</a></small></div></section>
<section class="decision"><div><p class="eyebrow">POSITION SIZING CHECK</p><h2>Liquidity is the first question.</h2><p>Compare your intended order with the indexed pool, then request a fresh execution quote. Pool liquidity is not executable depth. A daily price cannot establish slippage.</p><p>Pump.fun curve progress, Solana holder clusters, LP ownership and unlock schedules are not collected here. A token lock does not prove an LP lock.</p></div><div><p class="eyebrow">DEVFRIDGE ECONOMICS</p><h2>Follow the buy/burn path.</h2><p>${escape(brief.economics)}</p><a href="https://docs.devfridge.cool/program">Program & mint identity ↗</a> · <a href="https://docs.devfridge.cool/tokenomics">Tokenomics ↗</a><p class="program">Solana program <code>${PROGRAM}</code></p></div></section>
<section id="solana"><div class="section-heading"><div><p class="eyebrow">${brief.assets.filter(a => a.chain === 'solana').length} REGISTERED ASSETS</p><h2>Solana / Pump.fun</h2></div><a href="/graph.html">Explore their connections ↗</a></div><p class="section-note">Figures are dated observations. “Not observed” does not mean zero liquidity; bonding-curve markets may be absent from the index. Each card carries its own source timestamps.</p><div class="assets">${brief.assets.filter(a => a.chain === 'solana').map(assetCard).join('')}</div></section>
<section id="robinhood"><div class="section-heading"><div><p class="eyebrow">SEPARATE NETWORK · SEPARATE ASSETS</p><h2>Robinhood Chain</h2></div><span>${brief.assets.filter(a => a.chain === 'robinhood').length} registered contracts</span></div><p class="section-note">Matching tickers do not establish bridging or redemption rights. Holder accounts can include pools and custodians.</p><div class="assets">${brief.assets.filter(a => a.chain === 'robinhood').map(assetCard).join('')}</div></section>
<section class="reader-links" id="ai"><div><p class="eyebrow">SHARE THE EVIDENCE</p><h2>One link. The same facts.</h2><p>This page contains its evidence in the initial HTML. No wallet, login or graph rendering is needed to read it.</p><div class="actions"><button data-copy="${ORIGIN}/">Copy community link</button><a href="/brief.md">Read Markdown</a><a href="/brief.json">Read JSON</a><a href="/llms.txt">AI reading guide</a></div></div><div><label for="ai-prompt">Ask your AI</label><textarea id="ai-prompt" readonly>Read ${ORIGIN}/brief.md. Explain the Fridge, Scan and SDK product flow for a community pilot. Quote dated adoption and PASTA LP evidence. Separate wallet counts from external users and burn metrics from revenue. Preserve audit status, mint ${PASTA}, verified team commitments and the proposed nature of the 90-day plan.</textarea><button data-copy-prompt>Copy research prompt</button></div></section>
${contactSection(brief)}
<section id="sources"><div class="section-heading"><h2>Documentation & evidence</h2><a href="${KNOWLEDGE}">Full GitHub vault ↗</a></div><div class="doc-links">${brief.documents.map(doc => `<a href="${escape(doc.url)}">${escape(doc.title)}<small>${escape(statusText(doc))}</small></a>`).join('')}</div><p>GitHub refreshes the source snapshot daily at 06:17 UTC and on relevant changes. This brief checks the latest committed snapshot; delivery may be cached for five minutes. Failed sources retain dated observations. The 3D graph also checks for updates every five minutes while visible.</p></section>
</main><footer class="site-footer"><span>DevFridge Synapse · source-linked research</span><a href="https://connect.devfridge.cool">Official contacts</a><a href="https://github.com/mikeminer/devfridge/tree/master/synapse">Viewer source · AGPL-3.0</a><a href="/NOTICE.md">Magistra credits</a></footer><p class="copy-status" role="status" id="copy-status"></p></body></html>`;
}

export function renderMarkdown(brief) {
  const lines = [`# ${brief.title}`, '', `Canonical URL: ${ORIGIN}/`, `Canonical PASTA mint (Solana): ${PASTA}`, `Solana program: ${PROGRAM}`, `Snapshot attempt: ${brief.snapshot_attempted_at}`, `Delivery: ${brief.fallback ? 'saved fallback; live feed unavailable' : 'latest fetched GitHub snapshot'}`, `Registry: ${statusText(brief.registry)}`, '', brief.scope, '', brief.economics, '', '## Interpretation limits', ...brief.limits.map(s => '- ' + s), '', '## Assets'];
  lines.splice(lines.length - 1, 0, pitchMarkdown(brief));
  const { connect, team } = brief.contacts;
  lines.splice(lines.length - 1, 0, '## Official contacts & team', 'Only team members with verified PASTA commitment are included. Roles are project labels; commitment does not verify real-world identity.', `Connect: https://connect.devfridge.cool/ — ${statusText(connect)}`,
    ...(connect.data?.entries ?? []).map(c => `- ${c.group} — ${c.label}: ${safeURL(c.url)}`),
    `Team: https://team.devfridge.cool/ — ${statusText(team)}`, 'Roster source: https://scan.devfridge.cool/api/team',
    ...(team.data?.members ?? []).flatMap(m => [`- ${m.name} — ${m.role}; public wallet: ${m.wallet}; verified commitment checked ${m.commitment.checked_at}; evidence: ${safeURL(m.commitment.source)}`, ...m.contacts.map(c => `  - ${c.platform}: ${c.handle}${c.url ? ' — ' + safeURL(c.url) : ''}`)]), '');
  for (const a of brief.assets) {
    const p = a.largest_indexed_pool, c = a.chain_observation;
    lines.push('', `### ${a.name} ($${a.symbol}) — ${a.chain}`, `Address: ${a.address}`, `Chain evidence: ${statusText(c)}`, `Total supply: ${a.total_supply ?? 'not observed'}`, `Market evidence: ${statusText(a.market_observation)}`);
    if (a.chain === 'solana') lines.push(`Mint authority: ${authority(c.data, 'mint_authority')}; freeze authority: ${authority(c.data, 'freeze_authority')}`, `Largest indexed pool liquidity: ${usd(p?.liquidity?.usd)}; 24h pool volume: ${usd(p?.volume?.h24)}; price: ${usd(p?.priceUsd)}; FDV: ${usd(p?.fdv)}`, `Pool: ${p?.pairAddress ?? 'not observed'}`);
    else lines.push(`Holder accounts: ${a.market_observation.data?.holders_count ?? 'not observed'}; market depth and admin controls: not established`);
    lines.push('Locked percentage / unlock schedule: not collected; verify in https://scan.devfridge.cool', `Explorer: ${a.explorer}`, `Chain source: ${c.source ?? 'unavailable'}`, `Market source: ${a.market_observation.source ?? 'unavailable'}`, `Full note: ${a.graph}`);
  }
  lines.push('', '## Documentation', ...brief.documents.map(d => `- ${d.title}: ${d.url} (${statusText(d)})`), '', `Freshness and registry discrepancies: ${brief.sources.freshness}`, `Raw observations: ${SNAPSHOT_URL}`, `Official links and contacts: ${brief.sources.official}`, '', 'Refresh: daily at 06:17 UTC and on relevant GitHub changes; HTTP delivery cached for up to five minutes. No real-time execution quotes.', '');
  return lines.join('\n');
}

export const llmsText = `# DevFridge Synapse\n\nProduct, adoption and investor evidence for the official DevFridge ecosystem. The brief includes a KOL introduction, three-minute demo and proposed SDK pilot.\nCanonical PASTA identity: Solana ${PASTA}. Other PASTA tickers are unrelated.\n\n- [Concise investor brief](${ORIGIN}/brief.md): Start here for all asset identities, dated observations and limitations.\n- [Structured evidence](${ORIGIN}/brief.json): Product pitch, proposed pilot, protocol activity, PASTA LP evidence, verified team commitments and token controls.\n- [Human brief](${ORIGIN}/): The same evidence in readable HTML; no JavaScript required.\n- [Knowledge graph](${ORIGIN}/graph.html): Interactive notes and connections.\n- [Full vault](${KNOWLEDGE}): Detailed asset notes, docs and freshness report.\n- [Raw snapshot](${SNAPSHOT_URL}): All collected observations.\n- [Contact notes](${KNOWLEDGE}/contacts): Indexed Connect directory and Team roster, including CEO and project leader contacts.\n- [Official links](https://connect.devfridge.cool): Canonical contacts and asset registry.\n\nData refreshes daily, not in real time. Preserve mint/network identities and individual observation timestamps. Missing data is unknown, not zero. Pool liquidity is not executable depth or evidence of locked LP.\n`;
