import './style.css';
import {createScene} from './scene';
import {newRun,step,STEP} from './simulation.mjs';
import {setupWallet} from './wallet';
const el=(id:string)=>document.getElementById(id)!;
let state=newRun(),playing=false,paused=false,challengeRun=false,accumulator=0,last=0,frame=0,lastDraw=0;
const keys=new Set<string>(),pointers=new Map<number,string>();let brake=false;
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
const input=()=>({x:Number(keys.has('arrowright')||keys.has('d')||[...pointers.values()].includes('right'))-Number(keys.has('arrowleft')||keys.has('a')||[...pointers.values()].includes('left')),z:Number(keys.has('arrowdown')||keys.has('s')||[...pointers.values()].includes('down'))-Number(keys.has('arrowup')||keys.has('w')||[...pointers.values()].includes('up')),brake:brake||keys.has(' ')});
let view:ReturnType<typeof createScene>|undefined;
try{view=createScene(el('viewport'));}catch{el('viewport').textContent='WebGL could not start. Please enable hardware acceleration or try another browser.';(el('start') as HTMLButtonElement).disabled=true;}
const wallet=setupWallet(()=>{if(challengeRun){if(playing)pause('Access needs a fresh check. Resume in free practice.');challengeRun=false;el('mode-label').textContent='FREE PRACTICE';}});
let best=0;try{best=Number(localStorage.getItem('fridge-run-best'))||0;}catch{}el('best').textContent=best?`LOCAL BEST ${best.toLocaleString()} · UNVERIFIED`:'LOCAL BEST —';
function clearInput(){keys.clear();pointers.clear();brake=false;}
function loop(t:number){frame=0;if(document.hidden)return;const dt=Math.min(.1,(t-last)/1000||0);last=t;if(playing&&!paused){accumulator+=dt;while(accumulator>=STEP){step(state,input());accumulator-=STEP;if(state.event)el('toast').textContent=state.event;if(state.status!=='playing'){finish();break;}}el('cargo').textContent=`${state.cargo} / 6`;el('timer').textContent=state.time.toFixed(1);}if(t-lastDraw>=1000/30||!playing||paused){view?.update(state,t/1000,!reduce.matches&&!paused);lastDraw=t;}if(playing&&!paused)schedule();}
function schedule(){if(!frame&&!document.hidden)frame=requestAnimationFrame(loop);}
function start(isChallenge=false){if(!view||isChallenge&&!wallet.canChallenge())return;state=newRun();if(isChallenge)state.time=50;challengeRun=isChallenge;playing=true;paused=false;clearInput();accumulator=0;last=performance.now();document.body.classList.add('playing');el('run-overlay').hidden=true;el('hud').hidden=false;el('touch-controls').hidden=false;el('mode-label').textContent=isChallenge?'CHALLENGE · LOCAL SCORE':'FREE PRACTICE';el('toast').textContent='Collect six crates. Arrows / WASD to drive · Space to brake.';el('viewport').focus();schedule();}
function finish(){playing=false;paused=false;clearInput();el('run-overlay').hidden=false;el('resume').hidden=true;el('replay').hidden=false;el('result-kicker').textContent='LOCAL RESULT · UNVERIFIED';el('result-title').textContent=state.status==='won'?'Delivered ice-cold.':'The ice ran out.';el('result-text').textContent=state.status==='won'?`${state.score.toLocaleString()} points · ${state.time.toFixed(1)} seconds of ice saved · ${state.hits} heat hits. No prizes or ranked claims.`:`${state.cargo} of 6 crates collected. Try a wider line around the orange vents.`;if(state.score>best&&!challengeRun){best=state.score;try{localStorage.setItem('fridge-run-best',String(best));}catch{}el('best').textContent=`LOCAL BEST ${best.toLocaleString()} · UNVERIFIED`;}el('replay').focus();}
function pause(reason='Take a breather. Your delivery is paused.'){if(!playing)return;paused=true;clearInput();el('run-overlay').hidden=false;el('result-kicker').textContent='DELIVERY PAUSED';el('result-title').textContent='Parked. Still cool.';el('result-text').textContent=reason;el('resume').hidden=false;el('replay').hidden=true;view?.render();}
function resume(){if(!playing||el('access-dialog').matches('[open]')||el('help-dialog').matches('[open]'))return;paused=false;el('run-overlay').hidden=true;last=performance.now();accumulator=0;el('viewport').focus();schedule();}
el('start').onclick=()=>start();el('challenge').onclick=()=>start(true);el('replay').onclick=()=>start(challengeRun);el('resume').onclick=resume;el('pause').onclick=()=>pause();el('home').onclick=()=>{playing=false;paused=false;clearInput();state=newRun();document.body.classList.remove('playing');el('run-overlay').hidden=true;el('hud').hidden=true;el('touch-controls').hidden=true;el('mode-label').textContent='FREE PRACTICE';el('toast').textContent='Your courier is ready at the loading bay.';el('start').focus();view?.update(state,0,false);schedule();};
function showDialog(id:string){pause();clearInput();(el(id) as HTMLDialogElement).showModal();}
el('access-open').onclick=()=>showDialog('access-dialog');el('policy-open').onclick=()=>showDialog('access-dialog');el('how').onclick=()=>showDialog('help-dialog');el('help-ready').onclick=()=>(el('help-dialog') as HTMLDialogElement).close();
window.addEventListener('keydown',e=>{if(!playing||document.querySelector('dialog[open]'))return;const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown','w','a','s','d',' ','p','escape'].includes(k)){e.preventDefault();if((k==='p'||k==='escape')&&!e.repeat){paused?resume():pause();return;}if(!paused)keys.add(k);}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{clearInput();pause();});
document.querySelectorAll<HTMLButtonElement>('[data-move]').forEach(button=>{button.onpointerdown=e=>{if(!playing||paused)return;button.setPointerCapture(e.pointerId);pointers.set(e.pointerId,button.dataset.move!);e.preventDefault();};const release=(e:PointerEvent)=>pointers.delete(e.pointerId);button.onpointerup=release;button.onpointercancel=release;button.onlostpointercapture=release;});el('brake').onpointerdown=e=>{brake=true;el('brake').setPointerCapture(e.pointerId);};el('brake').onpointerup=()=>brake=false;el('brake').onpointercancel=()=>brake=false;el('brake').onlostpointercapture=()=>brake=false;
document.addEventListener('visibilitychange',()=>{if(document.hidden){pause('The page was backgrounded. Resume when you are ready.');cancelAnimationFrame(frame);frame=0;}else{last=performance.now();view?.render();if(!playing)schedule();}});
view?.renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();pause('Graphics context lost. Reload this page to recover; your local best is preserved.');el('resume').hidden=true;el('replay').hidden=true;});view?.renderer.domElement.addEventListener('webglcontextrestored',()=>{el('toast').textContent='Graphics restored. Reload to restart safely.';});
window.addEventListener('pagehide',()=>{cancelAnimationFrame(frame);frame=0;clearInput();});window.addEventListener('pageshow',()=>{last=performance.now();schedule();});reduce.addEventListener('change',()=>{view?.update(state,0,false);schedule();});
view?.update(state,0,false);schedule();
