import * as T from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {PICKUPS,VENTS} from './simulation.mjs';

export function createScene(container:HTMLElement){
 const renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;container.append(renderer.domElement);
 const scene=new T.Scene();scene.background=new T.Color('#173638');scene.fog=new T.Fog('#173638',30,65);
 const pmrem=new T.PMREMGenerator(renderer);const room=new RoomEnvironment();const env=pmrem.fromScene(room,.06);scene.environment=env.texture;room.dispose();pmrem.dispose();
 const camera=new T.PerspectiveCamera(36,1,.1,100);camera.position.set(12,18,22);camera.lookAt(0,0,0);
 const sunlight=new T.DirectionalLight('#ffe2b1',2.2);sunlight.position.set(-8,15,8);sunlight.castShadow=true;sunlight.shadow.mapSize.set(1024,1024);Object.assign(sunlight.shadow.camera,{left:-13,right:13,top:13,bottom:-13});sunlight.shadow.bias=-.001;scene.add(sunlight);scene.add(new T.HemisphereLight('#cceee4','#152d29',.65));
 const standard=(color:string,roughness=.7,metalness=0)=>new T.MeshStandardMaterial({color,roughness,metalness});
 const cream=standard('#d4d0ab',.5), teal=standard('#528f7f',.35,.2), dark=standard('#1f3532'), metal=standard('#adbbb1',.31,.9), rubber=standard('#1b2525',.94), ochre=standard('#d1a166',.5), wood=standard('#7f694d',.83);
 const paint=new T.MeshPhysicalMaterial({color:'#ddad65',metalness:.25,roughness:.32,clearcoat:.65});
 function box(parent:T.Object3D,w:number,h:number,d:number,x:number,y:number,z:number,mat:T.Material,r=.05){const mesh=new T.Mesh(new RoundedBoxGeometry(w,h,d,2,r),mat);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 function cyl(parent:T.Object3D,r:number,h:number,x:number,y:number,z:number,mat:T.Material){const m=new T.Mesh(new T.CylinderGeometry(r,r,h,20),mat);m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
 function label(text:string,bg:string,fg:string,width:number,height:number){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle=bg;ctx.fillRect(0,0,512,128);ctx.fillStyle=fg;ctx.font='bold 48px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,64);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;return new T.Mesh(new T.PlaneGeometry(width,height),new T.MeshStandardMaterial({map:tex,roughness:.65}));}
 // Coherent, deterministic paving: aggregate colour and matching surface relief.
 const cv=document.createElement('canvas');cv.width=cv.height=256;const ctx=cv.getContext('2d')!;ctx.fillStyle='#7b877b';ctx.fillRect(0,0,256,256);let seed=1247;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<7500;i++){const a=80+Math.floor(rnd()*75);ctx.fillStyle=`rgb(${a},${a+6},${a})`;ctx.fillRect(rnd()*256,rnd()*256,1.5,1.5);}ctx.strokeStyle='#445c53';ctx.lineWidth=3;ctx.strokeRect(0,0,256,256);ctx.beginPath();ctx.moveTo(128,0);ctx.lineTo(128,256);ctx.moveTo(0,128);ctx.lineTo(256,128);ctx.stroke();const paving=new T.CanvasTexture(cv);paving.wrapS=paving.wrapT=T.RepeatWrapping;paving.repeat.set(7,7);paving.colorSpace=T.SRGBColorSpace;const relief=paving.clone();relief.colorSpace=T.NoColorSpace;
 const floor=new T.MeshStandardMaterial({map:paving,bumpMap:relief,bumpScale:.035,roughness:.58,metalness:.08});box(scene,16,.6,17,0,-.35,0,dark,.2);box(scene,14.3,.12,14.8,0,0,0,floor);
 for(let i=-7;i<=7;i++){box(scene,.88,.22,.35,i,.13,-7.4,cream);box(scene,.88,.22,.35,i,.13,7.4,cream);}for(let i=-6;i<=6;i++){box(scene,.35,.22,.9,-7.2,.13,i,cream);box(scene,.35,.22,.9,7.2,.13,i,cream);}
 // Market cabinetry with awnings, framed doors, service signs and produce trays.
 for(const x of [-5,0,5]){box(scene,3.6,2.8,2.1,x,1.35,-8.5,teal,.12);box(scene,3.8,.22,2.5,x,2.82,-8.4,dark);box(scene,2.9,1.55,.1,x,1.5,-7.4,dark);box(scene,3.2,.2,1.25,x,.6,-7.1,wood);for(let a=-1;a<=1;a++){box(scene,.85,.22,.65,x+a,.82,-7.1,ochre);for(let j=0;j<3;j++){const fruit=new T.Mesh(new T.SphereGeometry(.12,8,8),a===0?ochre:teal);fruit.position.set(x+a+(j-1)*.2,1,-7.1);scene.add(fruit);}}for(let i=0;i<8;i++)box(scene,.44,.13,1.5,x-1.54+i*.44,2.5,-7, i%2?cream:teal);const sign=label(x===0?'COLD GOODS':x<0?'NIGHT MARKET':'ICE & EASY','#d6cca5','#294e44',2.7,.65);sign.position.set(x,2.05,-7.31);scene.add(sign);}
 for(const x of [-8.1,8.1])for(const z of [-4,2]){box(scene,1.3,1.1,2.5,x,.53,z,wood);box(scene,1.4,.15,2.6,x,1.15,z,cream);for(let i=0;i<3;i++)box(scene,.65,.08,.6,x,1.28,z+(i-1)*.7,teal);}
 for(const x of [-6.3,6.3]){cyl(scene,.06,4,x,2,-6,metal);box(scene,.9,.16,.45,x,4,-6,ochre);const lamp=new T.Mesh(new T.SphereGeometry(.12,12,8),new T.MeshStandardMaterial({color:'#fff0be',emissive:'#ffe7a3',emissiveIntensity:3}));lamp.position.set(x,3.83,-6);scene.add(lamp);}
 const cable=new T.CatmullRomCurve3([new T.Vector3(-6.3,4,-6),new T.Vector3(0,3.45,-6),new T.Vector3(6.3,4,-6)]);scene.add(new T.Mesh(new T.TubeGeometry(cable,30,.018,5,false),dark));for(let i=1;i<12;i++){const p=cable.getPoint(i/12);const bulb=new T.Mesh(new T.SphereGeometry(.075,8,8),new T.MeshStandardMaterial({color:'#ffe9b0',emissive:'#ffbb55',emissiveIntensity:2}));bulb.position.copy(p);scene.add(bulb);}
 box(scene,2.5,.03,2,0,.1,6,teal);for(let i=-3;i<=3;i++){const stripe=box(scene,.13,.02,1.7,i*.32,.13,6,cream,0);stripe.rotation.y=.3;}const homeSign=label('LOADING BAY','#254c42','#e9d49a',2,.5);homeSign.rotation.x=-Math.PI/2;homeSign.position.set(0,.16,7.05);scene.add(homeSign);
 const pickups=PICKUPS.map(([x,z],i)=>{const group=new T.Group();group.position.set(x,.18,z);scene.add(group);box(group,.65,.55,.65,0,.34,0,teal,.08);box(group,.7,.1,.7,0,.65,0,cream);box(group,.14,.57,.67,0,.35,0,metal);const ring=new T.Mesh(new T.TorusGeometry(.48,.025,6,32),new T.MeshStandardMaterial({color:'#a6f3b3',emissive:'#82dd9a',emissiveIntensity:1}));ring.rotation.x=Math.PI/2;ring.position.y=.08;group.add(ring);const number=label(String(i+1),'#528f7f','#f8efce',.26,.2);number.position.set(.2,.39,.331);group.add(number);return group;});
 VENTS.forEach(([x,z])=>{box(scene,1.25,.13,1.15,x,.15,z,dark);for(let i=-3;i<=3;i++)box(scene,.08,.04,.85,x+i*.14,.24,z,ochre);const glow=new T.Mesh(new T.RingGeometry(.58,.66,32),new T.MeshBasicMaterial({color:'#ef9551',side:T.DoubleSide}));glow.rotation.x=-Math.PI/2;glow.position.set(x,.12,z);scene.add(glow);});
 // Original refrigerated three-wheeler: rounded enamel shell, split windshield,
 // luggage rails, inset grille, wheel hubs, bumper, ice box and warm headlamps.
 const courier=new T.Group();scene.add(courier);box(courier,.92,.32,1.5,0,.38,0,dark,.12);box(courier,.9,.65,.75,0,.75,-.26,paint,.12);box(courier,.75,.32,.025,0,.9,-.646,new T.MeshPhysicalMaterial({color:'#173f40',metalness:.5,roughness:.16,clearcoat:1}));box(courier,.035,.35,.025,0,.9,-.668,metal);box(courier,1,.1,.9,0,1.13,-.24,cream);box(courier,.94,.75,.76,0,.9,.53,cream,.08);box(courier,.035,.55,.04,.3,.91,.93,metal);box(courier,.94,.025,.02,0,.92,.925,dark);box(courier,1,.1,.15,0,.29,-.78,metal);for(let i=-2;i<=2;i++)box(courier,.4,.023,.03,0,.54+i*.045,-.65,dark);for(const x of [-.33,.33])box(courier,.16,.12,.045,x,.69,-.655,new T.MeshStandardMaterial({color:'#ffffd8',emissive:'#ffdb99',emissiveIntensity:1.5}));
 const wheels:T.Mesh[]=[];for(const [x,z] of [[-.49,.46],[.49,.46],[0,-.58]]){const wheel=cyl(courier,.23,.15,x,.26,z,rubber);wheel.rotation.z=Math.PI/2;wheels.push(wheel);const hub=cyl(courier,.1,.17,x,.26,z,metal);hub.rotation.z=Math.PI/2;}for(const x of [-.37,.37])box(courier,.04,.1,.6,x,1.34,.5,metal);box(courier,.66,.05,.04,0,1.37,.22,metal);box(courier,.66,.05,.04,0,1.37,.79,metal);const logo=label('FR','#d4d0ab','#345c4a',.4,.23);logo.position.set(0,1.05,.922);courier.add(logo);
 function resize(){const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.position.set(10,19,camera.aspect<.9?27:22);camera.fov=camera.aspect<.9?44:36;camera.lookAt(0,0,-.5);camera.updateProjectionMatrix();render();}const observer=new ResizeObserver(resize);observer.observe(container);
 function render(){renderer.render(scene,camera);}
 function update(state:ReturnType<typeof import('./simulation.mjs').newRun>,time:number,animate:boolean){courier.position.set(state.x,.015,state.z);if(Math.hypot(state.vx,state.vz)>.1)courier.rotation.y=Math.atan2(-state.vx,-state.vz);wheels.forEach(w=>w.rotation.x+=Math.hypot(state.vx,state.vz)/60);pickups.forEach((p,i)=>{p.visible=!state.collected[i];p.position.y=.18+(animate?Math.sin(time*2+i)*.06:0);});render();}
 function dispose(){observer.disconnect();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});paving.dispose();relief.dispose();env.dispose();renderer.dispose();}
 resize();return{update,render,dispose,renderer};
}
