'use client';
import {useEffect,useState,useCallback,useRef} from 'react';
import {BrowserProvider,Contract,formatUnits,parseUnits,isAddress,ZeroAddress,type Eip1193Provider} from 'ethers';
import {TOPSHELF_ABI,TOPSHELF_CHAIN,EXPLORER,ERC20_ABI,type ShelfData} from '@/lib/topshelf/config';
import styles from './topshelf.module.css';
const short=(address:string)=>`${address.slice(0,6)}…${address.slice(-4)}`;
const amount=(raw:string,decimals:number)=>Number(formatUnits(raw,decimals)).toLocaleString('en-US',{maximumFractionDigits:6});
type Injected=Eip1193Provider&{on?:(event:string,listener:()=>void)=>void;removeListener?:(event:string,listener:()=>void)=>void};
function injected():Injected|undefined{return (window as unknown as {ethereum?:Injected;phantom?:{ethereum?:Injected}}).ethereum||(window as unknown as {phantom?:{ethereum?:Injected}}).phantom?.ethereum;}
export default function Leaderboard(){
 const [data,setData]=useState<ShelfData|null>(null),[wallet,setWallet]=useState(''),[displayName,setDisplayName]=useState(''),[season,setSeason]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tx,setTx]=useState(''),[nextCount,setNextCount]=useState('10'),[tokenAddress,setTokenAddress]=useState(''),[tokenFee,setTokenFee]=useState(''),[enabled,setEnabled]=useState(true),[withdrawToken,setWithdrawToken]=useState(''),[withdrawAmount,setWithdrawAmount]=useState(''),[recipient,setRecipient]=useState('');
 const [pending,setPending]=useState<{label:string;action:()=>Promise<void>}|null>(null);
 const requestId=useRef(0);
 const refresh=useCallback(async()=>{const id=++requestId.current;try{const q=new URLSearchParams();if(wallet)q.set('wallet',wallet);if(season)q.set('season',season);const res=await fetch(`/api/world/topshelf?${q}`,{cache:'no-store'});const body=await res.json();if(!res.ok)throw Error(body.error);if(id===requestId.current){setData(body);setError('');}}catch(e){if(id===requestId.current)setError(e instanceof Error?e.message:'Could not load TopShelf');}},[wallet,season]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),30000);return()=>clearInterval(timer);},[refresh]);
 useEffect(()=>{const p=injected();const changed=()=>{setWallet('');setPending(null);setNotice('Wallet or network changed. Reconnect before continuing.');};p?.on?.('accountsChanged',changed);p?.on?.('chainChanged',changed);return()=>{p?.removeListener?.('accountsChanged',changed);p?.removeListener?.('chainChanged',changed);};},[]);
 async function connect(){try{setError('');const p=injected();if(!p)throw Error('Open this page in an EVM wallet browser, or connect an installed EVM wallet.');await p.request({method:'eth_requestAccounts'});const hex='0x'+TOPSHELF_CHAIN.toString(16);try{await p.request({method:'wallet_switchEthereumChain',params:[{chainId:hex}]});}catch(e){if((e as {code?:number}).code!==4902)throw e;await p.request({method:'wallet_addEthereumChain',params:[{chainId:hex,chainName:'Robinhood Chain',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://rpc.mainnet.chain.robinhood.com'],blockExplorerUrls:[EXPLORER]}]});}const provider=new BrowserProvider(p);if((await provider.getNetwork()).chainId!==BigInt(TOPSHELF_CHAIN))throw Error('Switch to Robinhood Chain.');const account=await(await provider.getSigner()).getAddress();setWallet(account);setRecipient(account);const nameResponse=await fetch(`/api/world/topshelf/name?wallet=${account}`,{cache:'no-store'});if(nameResponse.ok)setDisplayName((await nameResponse.json()).name||'');setNotice('Robinhood wallet connected.');}catch(e){setError(e instanceof Error?e.message:'Wallet connection rejected');}}
 async function signedContract(ownerOnly=false){if(!data?.configured||!data.address)throw Error('TopShelf has not been activated.');const p=injected();if(!p||!wallet)throw Error('Connect your Robinhood wallet.');const provider=new BrowserProvider(p);if((await provider.getNetwork()).chainId!==BigInt(TOPSHELF_CHAIN))throw Error('Wrong network. Switch to Robinhood Chain.');const signer=await provider.getSigner();if((await signer.getAddress()).toLowerCase()!==wallet.toLowerCase())throw Error('Wallet changed. Reconnect.');const contract=new Contract(data.address,TOPSHELF_ABI,signer);if(ownerOnly&&(await contract.owner()).toLowerCase()!==wallet.toLowerCase())throw Error('Only the TopShelf owner can do this.');return{contract,signer};}
 async function send(label:string,method:string,args:unknown[],ownerOnly=false){setBusy(true);setPending(null);setError('');setNotice(`Confirm ${label.toLowerCase()} in your wallet.`);try{const{contract}=await signedContract(ownerOnly);const transaction=await contract[method](...args);setTx(transaction.hash);setNotice('Transaction submitted. Waiting for confirmation…');const receipt=await transaction.wait();if(receipt?.status!==1)throw Error('Transaction did not succeed.');setNotice(`${label} confirmed.`);await refresh();}catch(e){setError((e as {shortMessage?:string}).shortMessage||(e instanceof Error?e.message:'Transaction failed'));setNotice('');}finally{setBusy(false);}}
 async function prepareToken(){try{if(!isAddress(tokenAddress))throw Error('Enter a valid Robinhood token contract.');const{signer}=await signedContract(true),token=new Contract(tokenAddress,ERC20_ABI,signer);const[symbol,decimals]=await Promise.all([token.symbol(),token.decimals()]);const raw=parseUnits(tokenFee||'0',Number(decimals));if(enabled&&raw<=0n)throw Error('An enabled token needs a positive fee.');setPending({label:`${enabled?'Enable':'Disable'} ${symbol} (${tokenAddress}). Registration fee: ${formatUnits(raw,Number(decimals))} ${symbol}. Existing claim entitlements remain valid.`,action:()=>send('Token settings','configureToken',[tokenAddress,raw,enabled],true)});}catch(e){setError(e instanceof Error?e.message:'Invalid token settings');}}
 async function saveName(){setBusy(true);setError('');try{const normalized=displayName.normalize('NFKC').replace(/\s+/g,' ').trim();if(normalized.length<2||normalized.length>24)throw Error('Use a display name between 2 and 24 characters.');const p=injected();if(!p||!wallet)throw Error('Connect your Robinhood wallet.');const provider=new BrowserProvider(p),signer=await provider.getSigner(),account=await signer.getAddress();if(account.toLowerCase()!==wallet.toLowerCase())throw Error('Wallet changed. Reconnect.');const timestamp=Date.now(),message=`DevFridge World display name\nWallet: ${account}\nName: ${normalized}\nTimestamp: ${timestamp}`,signature=await signer.signMessage(message),response=await fetch('/api/world/topshelf/name',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wallet:account,name:normalized,timestamp,signature})}),body=await response.json();if(!response.ok)throw Error(body.error||'Could not save the display name.');setDisplayName(body.name);setNotice(`Display name saved as ${body.name}.`);await refresh();}catch(e){setError((e as {shortMessage?:string}).shortMessage||(e instanceof Error?e.message:'Could not save the display name.'));}finally{setBusy(false);}}
 function prepareWithdraw(){try{const token=data?.tokens.find(t=>t.address===withdrawToken);if(!token||!isAddress(recipient)||recipient===ZeroAddress)throw Error('Select a token and a valid recipient.');const raw=parseUnits(withdrawAmount,token.decimals);if(raw<=0n||raw>BigInt(token.available))throw Error('Amount exceeds the unreserved balance or is zero.');setPending({label:`Withdraw ${formatUnits(raw,token.decimals)} ${token.symbol} to ${recipient}. These funds will leave the available season pool.`,action:()=>send('Withdrawal','withdraw',[token.address,recipient,raw],true)});}catch(e){setError(e instanceof Error?e.message:'Invalid withdrawal');}}
 const isOwner=Boolean(wallet&&data&&wallet.toLowerCase()===data.owner.toLowerCase());const claims=data?.claimTokens.filter(t=>BigInt(t.claimable)>0n)||[];
 return <main className={styles.page}><div className={styles.shell}>
 <nav className={styles.nav}><a href="https://world.devfridge.cool/">← DevFridge World</a><a href="https://docs.devfridge.cool/world">Game guide ↗</a><button disabled={busy} onClick={connect}>{wallet?short(wallet):'Connect Robinhood wallet'}</button></nav>
 <header className={styles.hero}><p className={styles.eyebrow}>DEVFRIDGE WORLD / ROBINHOOD CHAIN</p><h1>TopShelf<span>Your best score.<br/>Your place on the shelf.</span></h1><p>Play on Solana. Register a verified score with a supported Robinhood token. Follow the seasonal ranking and claim your share when a distribution is approved.</p></header>
 {error&&<p role="alert" className={styles.error}>{error}</p>}{notice&&<p role="status" className={styles.notice}>{notice} {tx&&<a href={`${EXPLORER}/tx/${tx}`} target="_blank" rel="noopener noreferrer">View transaction ↗</a>}</p>}
 {!data?<p>Loading TopShelf…</p>:<>
 {!data.configured&&<section className={styles.notice}><h2>TopShelf is being prepared</h2><p>The contract is not connected yet. Score registration, claims and owner transactions will open after deployment and verification. No registrations or prize balances are being reported.</p></section>}
 <div className={styles.stats}><article><small>COLLECTING</small><strong>Season {data.currentSeason}</strong></article><article><small>PLAYERS · SEASON {data.season}</small><strong>{data.configured?data.players.toLocaleString():'—'}</strong></article><article><small>REGISTERED RUNS</small><strong>{data.configured?data.registrations.toLocaleString():'—'}</strong></article><article><small>OWNER’S NEXT WINNER COUNT</small><strong>{data.winnerCount||'Not set'}</strong></article></div>
 <section className={styles.card}><div className={styles.sectionTitle}><h2>Season leaderboard</h2><div><label>Season <input aria-label="Season number" type="number" min="1" max={data.currentSeason} value={season} placeholder={String(data.currentSeason)} onChange={e=>setSeason(e.target.value)}/></label><button onClick={()=>void refresh()}>Refresh</button></div></div><p>One place per wallet, ranked by its best verified score this season. Equal scores are ordered by wallet address.</p>
 <div className={styles.tableWrap}><table><thead><tr><th>Rank</th><th>Player</th><th>Best score</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.address}><td>{row.rank===1?'♛ ':''}{row.rank}</td><td><a title={row.address} href={`${EXPLORER}/address/${row.address}`} target="_blank" rel="noopener noreferrer"><strong>{row.name||short(row.address)}</strong>{row.name&&<small> · {short(row.address)}</small>}</a>{row.address.toLowerCase()===wallet.toLowerCase()&&' · You'}</td><td>{BigInt(row.score).toLocaleString('en-US')}</td></tr>)}</tbody></table></div>
 {!data.rows.length&&<p className={styles.empty}>{data.configured?'No scores registered in this season yet.':'The leaderboard will display confirmed on-chain scores once TopShelf is active.'}</p>}
 {data.next!==ZeroAddress&&<p>The first 100 players are shown. Full rankings are available through the contract’s paginated leaderboard.</p>}
 {data.block&&<small>Read from Robinhood block {data.block.toLocaleString()} · auto-refresh every 30 seconds</small>}</section>
 <section className={styles.card}><h2>Your leaderboard name</h2><p>Choose the public name shown beside your verified score. A wallet signature proves that you control this player address; saving a name costs no gas.</p>{wallet?<><label>Display name<input maxLength={24} value={displayName} placeholder="Your public name" onChange={e=>setDisplayName(e.target.value)}/></label><button disabled={busy} onClick={()=>void saveName()}>Sign & save name</button></>:<button onClick={connect}>Connect Robinhood wallet</button>}</section>
 <div className={styles.columns}><section className={styles.card}><h2>Season pool & entry tokens</h2><p>Registration fees are set by the owner per token. Playing remains free with a qualifying Solana timelock; recording a score is optional. ETH gas is separate.</p>{data.tokens.map(token=><div className={styles.token} key={token.address}><div><strong>{token.symbol}</strong><small>{token.enabled?`${formatUnits(token.fee,token.decimals)} per score`:'New payments disabled'}</small></div><div><strong>{amount(token.available,token.decimals)}</strong><small>available · {amount(token.reserved,token.decimals)} reserved for claims</small></div></div>)}{!data.tokens.length&&<p>Token fees will appear after the owner configures the contract.</p>}</section>
 <section className={styles.card}><h2>Your claims</h2><p>{data.claimPhase===2?`Claims are open for season ${data.claimSeason}.`:'No approved claim window is open.'}</p><p>Your share of each token is your winning score divided by the total score of the selected winners. The owner closes the claim window; remaining tokens carry forward to the next season.</p>{!wallet?<button onClick={connect}>Connect to check claims</button>:<>{claims.map(token=><div className={styles.token} key={token.address}><span>{formatUnits(token.claimable,token.decimals)} {token.symbol}</span><button disabled={busy} onClick={()=>void send('Claim','claim',[data.claimSeason,token.address])}>Claim</button></div>)}{claims.length>0?<button disabled={busy} onClick={()=>void send('Claims','claimAll',[data.claimSeason])}>Claim all tokens</button>:<p>No claimable allocation for this connected wallet.</p>}</>}</section></div>
 <section className={styles.disclosure}><strong>Owner-managed pool</strong><p>The owner chooses how many top players receive an allocation, approves distributions, closes claim windows, changes payment tokens and fees, and may withdraw unreserved funds, including amounts carried forward from closed distributions. Rewards and the availability of a future airdrop are not guaranteed.</p><p>Owner: <a href={`${EXPLORER}/address/${data.owner}`} target="_blank" rel="noopener noreferrer">{data.owner}</a>{data.address&&<> · Contract: <a href={`${EXPLORER}/address/${data.address}`} target="_blank" rel="noopener noreferrer">{data.address}</a></>}</p></section>
 {isOwner&&<section className={styles.card}><p className={styles.eyebrow}>OWNER CONTROLS</p><h2>Manage TopShelf</h2><fieldset disabled={busy||!data.configured}><div className={styles.columns}><div><h3>Distribution</h3><label>Number of top players<input type="number" min="1" step="1" value={nextCount} onChange={e=>setNextCount(e.target.value)}/></label><button onClick={()=>{if(!/^\d+$/.test(nextCount)||BigInt(nextCount)<1n){setError('Enter a positive whole number.');return;}void send('Winner count','setWinnerCount',[BigInt(nextCount)],true);}}>Save winner count</button><button disabled={data.activeDistribution!==0||data.winnerCount<1} onClick={()=>setPending({label:`Approve a proportional distribution for the top ${data.winnerCount} players in season ${data.currentSeason}. The available token pool will be reserved. Complete the snapshot to open claims.`,action:()=>send('Distribution approval','approveDistribution',[],true)})}>Approve distribution</button>
 {data.activeDistribution>0&&data.claimPhase===1&&<button onClick={()=>void send('Winner snapshot','captureWinners',[data.activeDistribution,25])}>Capture next 25 winners</button>}
 {data.activeDistribution>0&&data.claimPhase===2&&<button onClick={()=>setPending({label:`Close claims for season ${data.activeDistribution}. Unclaimed allocations will expire and the tokens will return to the pool for season ${data.currentSeason}.`,action:()=>send('Distribution closure','closeDistribution',[data.activeDistribution],true)})}>Close distribution & carry forward</button>}</div>
 <div><h3>Payment tokens</h3><label>Existing token<select value={tokenAddress} onChange={e=>{setTokenAddress(e.target.value);const t=data.tokens.find(t=>t.address===e.target.value);if(t){setTokenFee(formatUnits(t.fee,t.decimals));setEnabled(t.enabled);}}}><option value="">Add a new token below</option>{data.tokens.map(t=><option key={t.address} value={t.address}>{t.symbol} · {short(t.address)}</option>)}</select></label><label>Robinhood token contract<input value={tokenAddress} placeholder="0x…" onChange={e=>setTokenAddress(e.target.value)}/></label><label>Tokens per score<input inputMode="decimal" value={tokenFee} onChange={e=>setTokenFee(e.target.value)}/></label><label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Accept new payments</label><button onClick={()=>void prepareToken()}>Review token settings</button></div></div>
 <h3>Withdraw unreserved tokens</h3><div className={styles.columns}><label>Token<select value={withdrawToken} onChange={e=>setWithdrawToken(e.target.value)}><option value="">Select token</option>{data.tokens.map(t=><option key={t.address} value={t.address}>{t.symbol}</option>)}</select></label><label>Amount<input inputMode="decimal" value={withdrawAmount} onChange={e=>setWithdrawAmount(e.target.value)}/></label><label>Recipient<input value={recipient} onChange={e=>setRecipient(e.target.value)}/></label></div><button onClick={prepareWithdraw}>Review withdrawal</button></fieldset></section>}
 </>}
 {pending&&<div className={styles.overlay}><section role="dialog" aria-modal="true" aria-labelledby="shelf-review" className={styles.modal}><h2 id="shelf-review">Review transaction</h2><p>{pending.label}</p><p>Robinhood network fees are paid in ETH. Review the final transaction in your wallet.</p><button onClick={()=>void pending.action()}>Continue to wallet</button><button onClick={()=>setPending(null)}>Cancel</button></section></div>}
 <footer className={styles.nav}><a href="https://connect.devfridge.cool/">Official tokens & contacts ↗</a><a href="https://world.devfridge.cool/">Meet the cast ↗</a></footer>
 </div></main>;
}
