'use client';
import {useCallback,useEffect,useState} from 'react';
import {BrowserProvider,Contract,formatUnits,getAddress,isAddress,parseUnits,type Eip1193Provider} from 'ethers';
import {TOPSHELF_ABI,TOPSHELF_CHAIN,TOPSHELF_OWNER,EXPLORER,ERC20_ABI,type ShelfData} from '@/lib/topshelf/config';
import {ROBINHOOD_TOKENS} from '@/lib/official-tokens';
import styles from './admin.module.css';

const SCORE_VERIFIER='0x4e74b6433b65Dd93e077e2F732743F10EB00d8a5';
const CONTRACT_ADDRESS='0xc1DB49694E0DB50778c333350C8A553fDE221989';
const short=(value:string)=>`${value.slice(0,6)}…${value.slice(-4)}`;
type Injected=Eip1193Provider&{on?:(event:string,listener:()=>void)=>void;removeListener?:(event:string,listener:()=>void)=>void};
type Review={title:string;body:string;run:()=>Promise<void>};
type RegistrationStatus={ready:boolean;reason?:string;verifier?:string};
function injected():Injected|undefined{return (window as unknown as {ethereum?:Injected;phantom?:{ethereum?:Injected}}).ethereum||(window as unknown as {phantom?:{ethereum?:Injected}}).phantom?.ethereum;}

export default function TopShelfAdmin(){
 const [data,setData]=useState<ShelfData|null>(null),[registration,setRegistration]=useState<RegistrationStatus|null>(null),[wallet,setWallet]=useState(''),[currentVerifier,setCurrentVerifier]=useState(''),[tokenAddress,setTokenAddress]=useState(ROBINHOOD_TOKENS[0]?.address||''),[fee,setFee]=useState(''),[enabled,setEnabled]=useState(true),[notice,setNotice]=useState('Connect the TopShelf owner wallet to review the live settings.'),[error,setError]=useState(''),[tx,setTx]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState<Review|null>(null);
 const refresh=useCallback(async()=>{const [shelfResult,statusResult]=await Promise.allSettled([fetch('/api/world/topshelf',{cache:'no-store'}),fetch('/api/world/topshelf/register',{cache:'no-store'})]);let shelfWarning='';if(shelfResult.status==='fulfilled'){const shelf=await shelfResult.value.json();if(shelfResult.value.ok)setData(shelf);else shelfWarning=shelf.error||'Live token balances are temporarily unavailable.';}else shelfWarning='Live token balances are temporarily unavailable.';if(statusResult.status==='fulfilled'){const status=await statusResult.value.json();setRegistration(status);}else setRegistration({ready:false,reason:'Registration status is temporarily unavailable.'});setError(shelfWarning);},[]);
 useEffect(()=>{void refresh();},[refresh]);
 useEffect(()=>{const p=injected();const changed=()=>{setWallet('');setCurrentVerifier('');setReview(null);setNotice('Wallet or network changed. Reconnect before continuing.');};p?.on?.('accountsChanged',changed);p?.on?.('chainChanged',changed);return()=>{p?.removeListener?.('accountsChanged',changed);p?.removeListener?.('chainChanged',changed);};},[]);
 async function contract(){const p=injected();if(!p||!wallet)throw Error('Connect the owner wallet first.');const provider=new BrowserProvider(p);if((await provider.getNetwork()).chainId!==BigInt(TOPSHELF_CHAIN))throw Error('Switch to Robinhood Chain.');const signer=await provider.getSigner(),account=await signer.getAddress();if(account.toLowerCase()!==wallet.toLowerCase())throw Error('Wallet changed. Reconnect.');const topShelf=new Contract(CONTRACT_ADDRESS,TOPSHELF_ABI,signer);if((await topShelf.owner()).toLowerCase()!==account.toLowerCase())throw Error('Only the TopShelf owner can use this console.');return {topShelf,signer};}
 async function connect(){try{setError('');const p=injected();if(!p)throw Error('Open this page with an installed EVM wallet.');await p.request({method:'eth_requestAccounts'});const hex=`0x${TOPSHELF_CHAIN.toString(16)}`;try{await p.request({method:'wallet_switchEthereumChain',params:[{chainId:hex}]});}catch(e){if((e as {code?:number}).code!==4902)throw e;await p.request({method:'wallet_addEthereumChain',params:[{chainId:hex,chainName:'Robinhood Chain',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://rpc.mainnet.chain.robinhood.com'],blockExplorerUrls:[EXPLORER]}]});}const provider=new BrowserProvider(p),signer=await provider.getSigner(),account=await signer.getAddress(),topShelf=new Contract(CONTRACT_ADDRESS,TOPSHELF_ABI,signer),owner=getAddress(await topShelf.owner());if(owner.toLowerCase()!==account.toLowerCase())throw Error(`Connected wallet is not the TopShelf owner (${short(owner)}).`);setWallet(account);setCurrentVerifier(getAddress(await topShelf.verifier()));setNotice('Owner wallet connected. Review a change before sending it to the wallet.');}catch(e){setError(e instanceof Error?e.message:'Wallet connection rejected.');}}
 async function send(label:string,method:string,args:unknown[]){setBusy(true);setReview(null);setError('');setNotice(`Confirm ${label.toLowerCase()} in your wallet.`);try{const {topShelf}=await contract(),transaction=await topShelf[method](...args);setTx(transaction.hash);setNotice('Transaction submitted. Waiting for confirmation…');const receipt=await transaction.wait();if(receipt?.status!==1)throw Error('Transaction did not succeed.');setNotice(`${label} confirmed on Robinhood Chain.`);setCurrentVerifier(getAddress(await topShelf.verifier()));await refresh();}catch(e){setError((e as {shortMessage?:string}).shortMessage||(e instanceof Error?e.message:'Transaction failed.'));setNotice('');}finally{setBusy(false);}}
 function prepareVerifier(){setError('');setReview({title:'Activate score verifier',body:`TopShelf will trust ${SCORE_VERIFIER} to authorize verified game scores. This address cannot move player funds.`,run:()=>send('Verifier activation','setVerifier',[SCORE_VERIFIER])});}
 async function prepareToken(){try{setError('');if(!isAddress(tokenAddress))throw Error('Select or enter a valid Robinhood token contract.');const {signer}=await contract(),token=new Contract(tokenAddress,ERC20_ABI,signer),[symbol,decimals]=await Promise.all([token.symbol(),token.decimals()]),raw=parseUnits(fee||'0',Number(decimals));if(enabled&&raw<=0n)throw Error('An enabled token needs a positive fee.');setReview({title:'Update payment token',body:`${enabled?'Enable':'Disable'} ${symbol} (${getAddress(tokenAddress)}). Fixed registration fee: ${formatUnits(raw,Number(decimals))} ${symbol}.`,run:()=>send('Token settings','configureToken',[tokenAddress,raw,enabled])});}catch(e){setError(e instanceof Error?e.message:'Invalid token settings.');}}
 const ownerConnected=wallet.toLowerCase()===TOPSHELF_OWNER.toLowerCase(),verifierActive=currentVerifier.toLowerCase()===SCORE_VERIFIER.toLowerCase();
 return <main className={styles.page}><div className={styles.shell}>
  <nav className={styles.nav}><a href="/">← DevFridge World</a><a href="/leaderboard">Leaderboard & owner controls ↗</a></nav>
  <header className={styles.hero}><p className={styles.eyebrow}>DEVFRIDGE WORLD / ROBINHOOD CHAIN</p><h1>TopShelf admin</h1><p>Activate verified score registration and manage the tokens accepted by the TopShelf contract.</p></header>
  {error&&<p role="alert" className={styles.error}>{error}</p>}<p role="status" className={registration?.ready?styles.success:styles.status}>{notice} {tx&&<a href={`${EXPLORER}/tx/${tx}`} target="_blank" rel="noopener noreferrer">View transaction ↗</a>}</p>
  <section className={styles.card}><h2>Contract access</h2><dl className={styles.facts}><dt>TopShelf</dt><dd><a href={`${EXPLORER}/address/${CONTRACT_ADDRESS}`} target="_blank" rel="noopener noreferrer">{CONTRACT_ADDRESS}</a></dd><dt>Required owner</dt><dd>{TOPSHELF_OWNER}</dd><dt>Score verifier</dt><dd>{SCORE_VERIFIER}</dd><dt>Registration</dt><dd>{registration?.ready?'Ready':registration?.reason||'Checking…'}</dd></dl><button disabled={busy} onClick={connect}>{wallet?`${short(wallet)} connected`:'Connect owner wallet'}</button></section>
  <section className={styles.card}><p className={styles.eyebrow}>STEP 1</p><h2>Trust the score verifier</h2><p>The server validates the finished run, the linked Solana wallet and the qualifying timelock before it signs a one-use score receipt.</p>{currentVerifier&&<p>Current verifier: <strong>{currentVerifier}</strong></p>}<button disabled={busy||!ownerConnected||verifierActive} onClick={prepareVerifier}>{verifierActive?'Verifier active':'Review verifier activation'}</button></section>
  <section className={styles.card}><p className={styles.eyebrow}>STEP 2</p><h2>Set payment tokens</h2><p>Set the exact token quantity charged for optional score registration. The contract stores a fixed quantity; it does not automatically track the dollar price.</p><label>Official Robinhood token<select value={tokenAddress} onChange={e=>{setTokenAddress(e.target.value);const live=data?.tokens.find(t=>t.address.toLowerCase()===e.target.value.toLowerCase());if(live){setFee(formatUnits(live.fee,live.decimals));setEnabled(live.enabled);}}}>{ROBINHOOD_TOKENS.map(token=><option key={token.address} value={token.address}>{token.symbol} · {short(token.address)}</option>)}</select></label><label>Robinhood token contract<input value={tokenAddress} onChange={e=>setTokenAddress(e.target.value)} placeholder="0x…"/></label><label>Tokens per score registration<input inputMode="decimal" value={fee} onChange={e=>setFee(e.target.value)} placeholder="Enter the fixed quantity"/></label><label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Accept new score payments</label><button disabled={busy||!ownerConnected} onClick={()=>void prepareToken()}>Review token settings</button>
   {data?.tokens.length?<><h3>Current contract tokens</h3>{data.tokens.map(token=><div className={styles.token} key={token.address}><div><strong>{token.symbol}</strong><small>{token.address}</small></div><div><strong>{token.enabled?'Enabled':'Disabled'}</strong><small>{formatUnits(token.fee,token.decimals)} per score</small></div></div>)}</>:<p>No payment token has been configured yet.</p>}
  </section>
  <section className={styles.card}><h2>More owner controls</h2><p>Winner count, distribution approval, claim closure and withdrawals remain available on the leaderboard.</p><a href="/leaderboard">Open leaderboard owner controls ↗</a></section>
  {review&&<div className={styles.overlay}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="review-title"><h2 id="review-title">{review.title}</h2><p>{review.body}</p><p>Robinhood network fees are paid in ETH. Your wallet will show the final transaction before it is submitted.</p><button disabled={busy} onClick={()=>void review.run()}>Continue to wallet</button><button className={styles.secondary} onClick={()=>setReview(null)}>Cancel</button></section></div>}
 </div></main>;
}
