'use client';
import { useState } from 'react';
import dynamic from 'next/dynamic';
import styles from './skill.module.css';
import ProgramStory from './ProgramStory';
import { INSTALL_PROMPT, SUBMISSION_PROMPT, SUBMISSION_INTRO, SUBMISSION_STEPS, SHOWCASE_STATUS } from '@/lib/game-builder-prompts';

const Scene = dynamic(() => import('./SkillScene'), { ssr: false, loading: () => <div className={styles.scenePlaceholder}>Preparing your little world…</div> });
const DOWNLOAD = '/world/skill/downloads/devfridge-game-builder';

const examples = [
  { id: 'runner', number: '01', name: 'Meme on the run', genre: '3D endless runner', detail: 'One thumb. Three lanes. Your meme outrunning the chaos.', prompt: 'Build a Three.js endless runner for my Pump.fun token. Ask for the exact mint, lock amount and duration. Include three-lane swipe controls, keyboard controls, collectible combos, a complete loss/restart loop, Phantom desktop/mobile and DevFridge access. Keep the HUD clear of the track. Start with local personal bests and no paid entry.' },
  { id: 'drift', number: '02', name: 'Community drift club', genre: '3D arcade drifting', detail: 'A tiny track with a big personality. Chase your best lap.', prompt: 'Build a stylized Three.js drift game around my meme. Interview me about the token, character, handling and lock rule. Support keyboard steering and mobile steering buttons, lap timing and restart, Phantom and DevFridge timelocks. Use original or licensed assets. Label personal bests local; ask before adding authoritative competitive scores.' },
  { id: 'arena', number: '03', name: 'Last meme standing', genre: '3D arena survival', detail: 'Dodge the swarm. Collect upgrades. Survive another wave.', prompt: 'Build a single-player Three.js survival arena for my token community, with virtual joystick and keyboard movement, auto-attack, escalating waves and win/loss screens. Ask for mint, assets and DevFridge gate policy. Use Phantom on desktop/mobile. Do not imply real multiplayer or rewards unless we design those separately.' },
  { id: 'puzzle', number: '04', name: 'Stack the lore', genre: '3D physics puzzle', detail: 'Merge, balance and discover the next form of your mascot.', prompt: 'Build an original Three.js physics stacking puzzle for my Pump.fun meme. Ask about merge rules, assets, mint and timelock threshold. Implement touch drag/drop and pointer aim, fixed-step physics, sound, restart and score-image sharing. Use DevFridge plus Phantom without copying World characters or imposing its ten-token rules.' },
  { id: 'explore', number: '05', name: 'Holder hideout', genre: '3D exploration', detail: 'A community clubhouse with doors your token can open.', prompt: 'Build an explorable Three.js clubhouse with keyboard and touch controls. Ask which rooms or characters my token timelocks unlock, the exact mint, minimum amount and duration. Include Phantom, DevFridge onboarding, a live lock badge and accessible menus. A single-player prototype is fine; ask before adding real-time social networking.' },
  { id: 'season', number: '06', name: 'Season challengers', genre: 'Competitive game', detail: 'A verified leaderboard, designed as a separate trusted system.', prompt: 'Help me design and build a competitive Three.js game with Solana DevFridge access. Interview me about gameplay and rewards. Separate wallet ownership, timelock eligibility and live score authority. Evaluate TopShelf as an optional Robinhood integration, confirm operator support, and never submit arbitrary browser scores to its production service. Explain bot limitations and test mobile interruptions before enabling rewards.' },
];
const VISUAL_BRIEF = 'Use detailed models, realistic PBR textures, natural material scale, environment reflections and soft contact shadows. Ask about art direction; optimize texture sizes and draw calls for mobile. Do not deliver placeholder cubes as finished art.';
const modules = ['Live lock badge', 'Scanner report', 'Telegram links', 'Score-image sharing', 'Competitive leaderboard'];

function CopyButton({ text, label = 'Copy prompt' }: { text: string; label?: string }) {
  const [state, setState] = useState('');
  async function copy() {
    try { await navigator.clipboard.writeText(text); setState('Copied'); }
    catch { setState('Copy unavailable — select the prompt text below.'); }
  }
  return <div className={styles.copyAction}><button onClick={copy} type="button">{state === 'Copied' ? 'Copied ✓' : label} <span aria-hidden="true">↗</span></button><span role="status">{state !== 'Copied' ? state : 'Ready to paste into your AI coding agent.'}</span></div>;
}

export default function SkillLanding() {
  const [genre, setGenre] = useState('runner');
  const [mint, setMint] = useState('');
  const [minimum, setMinimum] = useState('');
  const [duration, setDuration] = useState('Ask me which duration policy fits');
  const [selected, setSelected] = useState(['Live lock badge', 'Scanner report']);
  const [client, setClient] = useState('Codex');
  const current = examples.find(example => example.id === genre)!;
  const prompt = `Use $devfridge-game-builder to build a game in this genre: ${current.genre}, for my Pump.fun meme.\n\nFirst read the installed skill and its relevant references. Interview me about missing game, token and deployment decisions before committing to the design.\n\nToken mint or Pump.fun URL: ${mint.trim() || 'Ask me for the exact Solana mint; do not choose one for me.'}\nMinimum tokens to lock: ${minimum.trim() || 'Ask me; do not assume the World threshold.'}\nDuration policy: ${duration}.\nOptional modules: ${selected.length ? selected.join(', ') : 'None for the first version'}.\n\nBuild with Three.js for desktop and mobile, including Phantom desktop and mobile-browser access, first-lock onboarding through DevFridge, and SDK-based lock checks. Verify mint ownership, decimals and compatibility. Ask about characters, assets, controls, scoring and hosting. ${VISUAL_BRIEF} Keep menus clear of gameplay. Distinguish practice, authenticated access and verified competitive scores. Explain reuse of the existing DevFridge Solana program, distinguish embedded security metadata, verified builds and independent audits using current evidence, explain why players might return, and the 2% redemption fee that buys and burns PASTA. Disclose expiry and costs before locking; distinguish developer-support intent from direct treasury income. Do not create real transactions or promise rewards. Deliver runnable code and test the full game loop, wallet failure cases, touch controls and audio recovery.\n\nSkill and downloads: https://world.devfridge.cool/skill`;
  const install = client === 'Codex' ? 'Extract the ZIP. Place the devfridge-game-builder folder in your project’s .agents/skills/ directory, then invoke $devfridge-game-builder in Codex. If your Codex version uses a different skill directory, follow its current settings.' : client === 'Claude Code' ? 'Extract the ZIP into .claude/skills/ in your project, keeping devfridge-game-builder/SKILL.md and its resources together. Invoke /devfridge-game-builder. Replace the $ invocation in the example prompts with this slash command.' : 'Use the ZIP with an agent that supports Agent Skills, following its installation instructions. Otherwise give your coding agent SKILL.md and the referenced files, and explicitly ask it to follow the skill. A copied prompt alone does not install it.';
  return <main className={styles.page}>
    <nav className={styles.nav} aria-label="Game builder navigation"><a className={styles.brand} href="https://world.devfridge.cool/">▧ DEVFRIDGE <span>WORLD / BUILD</span></a><div><a href="#quick-install">Install with AI</a><a href="#examples">Ideas</a><a href="#submit">Submit your game</a><a href="#install">Get the skill <span aria-hidden="true">↗</span></a></div></nav>
    <header className={styles.hero}>
      <div className={styles.heroCopy}><p className={styles.eyebrow}><i/> THE GAME BUILDER SKILL · v1.4</p><h1>Your meme.<br/>A world<br/><em>to play.</em></h1><p className={styles.lead}>Turn your meme into a character worth coming back for. Build a 3D browser game where DevFridge timelocks unlock access, with Phantom on desktop and mobile.</p>
        <section className={styles.quickInstall} id="quick-install" aria-labelledby="quick-install-title"><h2 id="quick-install-title">Start here. Install the skill.</h2><p>Open your project in a coding agent and paste this prompt. It installs the skill, then helps you shape your game.</p><textarea aria-label="Skill installation prompt" readOnly value={INSTALL_PROMPT} spellCheck={false}/><CopyButton text={INSTALL_PROMPT} label="Copy installation prompt"/><a href="#install">Prefer a manual install? See the steps ↓</a></section>
        <div className={styles.actions}><a className={styles.primary} href={`${DOWNLOAD}.zip`} download>Download the skill <span>↓</span></a><a className={styles.secondary} href="#prompt">Make my prompt ↗</a></div><p className={styles.micro}>Open Agent Skills format · Desktop + mobile · Your token, your rules</p></div>
      <div className={styles.preview}><div className={styles.previewBar}><span><i/> CONCEPT LAB</span><span>THREE.JS / PBR</span></div><div className={styles.scene}><Scene genre={genre}/></div><div className={styles.previewCaption}><span>{current.genre}</span><strong>Small world. Endless possibilities.</strong><div className={styles.sceneTabs}>{examples.slice(0,3).map(item => <button key={item.id} aria-pressed={genre === item.id} onClick={() => setGenre(item.id)}>{item.id}</button>)}</div><p>PBR material study · detailed models, textured surfaces and studio lighting. Your AI builds the actual game.</p></div></div>
    </header>
    <div className={styles.strip}><span>01 / BRING A MEME</span><b>+</b><span>02 / SHAPE THE GAME</span><b>+</b><span>03 / LOCK TO UNLOCK</span><b>→</b><span>PLAY ANYWHERE</span></div>
    <section className={styles.retention} id="why-lock">
      <div className={styles.sectionHeading}><p className={styles.eyebrow}>LOCK TO UNLOCK. PLAY TO BELONG.</p><h2>A meme gets attention.<br/>A good game earns the next visit.</h2><p>A token in a wallet gives a community something to own. A playable character gives it something to do. DevFridge connects the two: players commit tokens for a chosen time and unlock a place in your game.</p></div>
      <div className={styles.steps}>{[
        ['IDENTITY', 'That meme is me.', 'Turn your token’s character and lore into a playable identity. Give holders a way to show up as part of their community.'],
        ['COMMITMENT', 'I’m in for this season.', 'Players choose a timelock that meets your access rules. The commitment has a clear end date; tokens stay locked until then.'],
        ['REASONS TO RETURN', 'One more run.', 'Master a level, beat a personal best or join a community challenge. Build a repeat-play loop that makes the unlocked access worth using.'],
      ].map(([tag,title,text]) => <article key={tag}><span>{tag}</span><h3>{title}</h3><p>{text}</p></article>)}</div>
      <div className={styles.protocol}><span className={styles.eyebrow}>ONE SOLANA PROGRAM. YOUR GAME’S RULES.</span><h3>Connect → Lock → Unlock → Play → Return</h3><p>Games using this gate read timelocks in the existing <a href="https://docs.devfridge.cool/program" target="_blank" rel="noopener noreferrer">DevFridge Solana program ↗</a> through the SDK/API. You choose the supported mint, amount, duration and character access. Tokens sit in program-owned vaults; your game does not need its own timelock contract.</p><p>Players cannot withdraw early. Access lasts while the lock meets your rules, and redemption becomes available after expiry, subject to the token’s redemption route.</p></div>
      <p className={styles.note}>The retention idea is identity + voluntary commitment + enjoyable progress. A lock creates an access window; gameplay earns the return visit. Measure returning players separately from locked tokens. Neither retention nor token price growth is guaranteed.</p>
    </section>
    <ProgramStory/>
    <section className={styles.section} id="how"><div className={styles.sectionHeading}><p className={styles.eyebrow}>A BUILDING PARTNER, WITH CONTEXT</p><h2>It asks the right questions.<br/>Then it helps you ship.</h2><p>A practical skill for an AI coding agent. It supplies the DevFridge integration knowledge; your agent writes and tests the game in your project.</p></div><div className={styles.steps}>{[
      ['01', 'Find your game', 'Runner, drifter, puzzle or something stranger. The AI asks about gameplay, characters, assets and the way your community wants to play.'],
      ['02', 'Set your access rules', 'Your mint, your minimum and your lock duration. One token can unlock the game; several can unlock different characters.'],
      ['03', 'Build for real screens', 'Three.js, touch controls, Phantom, clear onboarding and mobile audio recovery. Test a complete game loop before adding more.'],
    ].map(([number,title,text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className={styles.studio} id="prompt"><div className={styles.sectionHeading}><p className={styles.eyebrow}>PROMPT STUDIO</p><h2>Start with your idea.</h2><p>Fill in what you know. Leave the rest blank and the skill will ask.</p></div><div className={styles.studioGrid}><div className={styles.config}><label>What are we building?<select value={genre} onChange={event => setGenre(event.target.value)}>{examples.map(item => <option value={item.id} key={item.id}>{item.genre}</option>)}</select></label><label>Solana mint or Pump.fun URL<input value={mint} onChange={event => setMint(event.target.value)} placeholder="Your token’s full address" maxLength={180}/></label><div className={styles.pair}><label>Minimum whole tokens<input value={minimum} onChange={event => setMinimum(event.target.value)} placeholder="Ask me first" inputMode="decimal" maxLength={40}/></label><label>Timelock duration<select value={duration} onChange={event => setDuration(event.target.value)}><option>Ask me which duration policy fits</option><option>Any active lock; no extra duration minimum</option><option>At least 30 days original lock duration</option><option>At least 7 days remaining</option></select></label></div><fieldset><legend>Optional ingredients</legend>{modules.map(module => <label className={styles.check} key={module}><input type="checkbox" checked={selected.includes(module)} onChange={() => setSelected(previous => previous.includes(module) ? previous.filter(item => item !== module) : [...previous,module])}/>{module}</label>)}</fieldset><p className={styles.note}>A mint is verified during development. This form does not connect a wallet, check eligibility or submit a transaction.</p></div><div className={styles.prompt}><div className={styles.promptHeader}><span>YOUR BUILD BRIEF</span><span>.prompt</span></div><textarea aria-label="Generated game builder prompt" readOnly value={prompt}/><CopyButton key={prompt} text={prompt}/></div></div></section>
    <section className={styles.section} id="examples"><div className={styles.sectionHeading}><p className={styles.eyebrow}>SIX STARTING POINTS. YOUR OWN LORE.</p><h2>What will your meme become?</h2><p>Example briefs, not ready-made games. Copy one and let the skill interview you.</p></div><div className={styles.examples}>{examples.map(item => <article key={item.id}><div className={styles.exampleTop}><span>{item.number}</span><span>{item.genre}</span></div><h3>{item.name}</h3><p>{item.detail}</p><details><summary>Read the prompt</summary><p className={styles.examplePrompt}>Use $devfridge-game-builder. {item.prompt} {VISUAL_BRIEF}</p></details><CopyButton text={`Use $devfridge-game-builder. ${item.prompt} ${VISUAL_BRIEF}`} /></article>)}</div></section>
    <section className={styles.ecosystem}><div className={styles.sectionHeading}><p className={styles.eyebrow}>CHOOSE YOUR INGREDIENTS</p><h2>One game.<br/>A connected ecosystem.</h2><p>Start with the core. Add the components that serve your game.</p><a href="https://ecosystem.devfridge.cool/" target="_blank" rel="noopener noreferrer">Explore the whole kitchen ↗</a></div><div className={styles.moduleGrid}>{[
      ['CORE','Fridge + SDK','Timelocks become access. Use your own supported mint, quantities and duration policy.','https://sdk.devfridge.cool/'],
      ['WALLET','Phantom','Desktop extension and mobile wallet browser, with sign-in and clear first-lock onboarding.','https://docs.phantom.com/solana/integrating-phantom'],
      ['VISIBILITY','Scanner + badge','Let players inspect the mint and see live supply-lock evidence beside the game token.','https://scan.devfridge.cool/badge'],
      ['COMMUNITY','FrigoPasta + sharing','Optional Telegram tools, token information and shareable score images.','https://bot.devfridge.cool/'],
      ['ADVANCED','Seasons + TopShelf','Design score authority first. Robinhood integration needs separate configuration and operator support.','https://world.devfridge.cool/leaderboard'],
      ['DISCOVERY','The wider kitchen','Connect, Health, Synapse, Team, Feature, Capital and verified bridge routes — selected when useful.','https://ecosystem.devfridge.cool/integrate'],
    ].map(([tag,title,text,href]) => <a key={title} href={href} target="_blank" rel="noopener noreferrer"><span>{tag} ↗</span><h3>{title}</h3><p>{text}</p></a>)}</div></section>
    <section className={styles.fee} id="redeem-fee" aria-labelledby="redeem-fee-title">
      <div className={styles.feeNumber}><strong>2%</strong><span>ON REDEMPTION</span><small>Network costs are separate.</small></div>
      <div className={styles.sectionHeading}><p className={styles.eyebrow}>USE THE ECOSYSTEM. SUPPORT ITS BUILDER.</p><h2 id="redeem-fee-title">The PASTA connection.</h2><p>When a player redeems after expiry, DevFridge uses a <strong>2% fee</strong> to buy and burn <strong>PASTA</strong>. If the locked token is PASTA, the fee is burned directly.</p><p><strong>PASTA is pappardelle.sol’s developer token.</strong> The project’s support model connects ecosystem usage to PASTA buy-and-burn, with the aim of supporting continued development and infrastructure sustainability.</p><div className={styles.feeFlow}><span>Redeem after expiry</span><b>→</b><span>2% protocol fee</span><b>→</b><span>Buy PASTA + burn</span></div><p className={styles.note}>The fee is spent on buying and burning tokens. It is not a direct payment to an infrastructure or developer treasury, and does not guarantee developer income or a price increase.</p><p className={styles.note}>Example: redeeming a 100,000-token vault leaves 98,000 tokens after the 2,000-token protocol fee, before separate network costs and token-specific effects. Non-PASTA redemption requires an executable Jupiter route. Explain the fee, unlock date and route limitations before players lock. Players do not need to own PASTA separately to lock another supported game token.</p><a className={styles.feeLink} href="https://docs.devfridge.cool/tokenomics" target="_blank" rel="noopener noreferrer">Read the fee and burn mechanics ↗</a></div>
    </section>
    <section className={styles.section} id="submit"><div className={styles.sectionHeading}><p className={styles.eyebrow}>YOUR CODING AGENT + THE DEVFRIDGE SKILL</p><h2>Submit through your agent.<br/>No Git experience needed.</h2><p>{SUBMISSION_INTRO}</p><p>Copy this prompt into your own coding agent with the DevFridge Game Builder skill installed. Your agent submits the game; this website explains the process and displays the reviewed projects.</p><p>{SHOWCASE_STATUS}</p></div><div className={styles.steps}>{SUBMISSION_STEPS.map(([number,title,text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div><CopyButton text={SUBMISSION_PROMPT} label="Copy guided submission prompt"/><div className={styles.actions}><a className={styles.primary} href="https://hackathon.devfridge.cool/projects">Explore the project gallery ↗</a><a className={styles.secondary} href="https://hackathon.devfridge.cool/#submit">Hackathon submission guide ↗</a></div></section>
    <section className={styles.install} id="install"><div><p className={styles.eyebrow}>PUT IT IN YOUR TOOLBOX</p><h2>Small download.<br/>A complete playbook.</h2><p>Includes the developer interview, retention and fee messaging, program verification and reuse guide, ecosystem map, SDK and Phantom guides, mobile delivery checklist, competitive-mode guidance, a guided hackathon PR submission workflow and an exact-amount lock evaluator with tests.</p><div className={styles.actions}><a className={styles.primary} href={`${DOWNLOAD}.zip`} download>Download ZIP ↓</a><a className={styles.secondary} href={`${DOWNLOAD}.skill`} download>.skill archive ↓</a></div><p className={styles.note}>The .skill file contains the same ZIP package. Use it only if your agent supports this import format.</p><a href={`${DOWNLOAD}/SKILL.md`} target="_blank" rel="noopener noreferrer">Read SKILL.md ↗</a><a className={styles.sourceLink} href="https://github.com/mikeminer/devfridge/tree/master/skills/devfridge-game-builder" target="_blank" rel="noopener noreferrer">Browse all source files ↗</a></div><div className={styles.installBox}><div className={styles.clientTabs}>{['Codex','Claude Code','Other agents'].map(name => <button key={name} onClick={() => setClient(name)} aria-pressed={client===name}>{name}</button>)}</div><h3>Install, then start a conversation.</h3><p>{install}</p><pre>{`devfridge-game-builder/\n├── SKILL.md\n├── agents/openai.yaml\n├── references/\n│   ├── discovery.md\n│   ├── retention-and-economics.md\n│   ├── program-and-verification.md\n│   ├── ecosystem.md\n│   ├── sdk-access.md\n│   ├── phantom.md\n│   ├── game-delivery.md\n│   ├── visual-realism.md\n│   ├── competition.md\n│   ├── hackathon-submission.md\n│   └── sources.md\n└── assets/\n    ├── timelock-gate.mjs\n    └── timelock-gate.test.mjs`}</pre><p className={styles.note}>Agent Skills is a folder format, not a hosted game generator. Your agent needs a coding workspace and development tools. <a href="https://agentskills.io/specification" target="_blank" rel="noopener noreferrer">Format specification ↗</a></p></div></section>
    <section className={styles.faq}><p className={styles.eyebrow}>BEFORE YOU BUILD</p><h2>A few things to know.</h2>{[
      ['Does my Pump.fun token work automatically?','The skill verifies the full mint, token program, decimals and extensions. Current Fridge integration uses Solana Token-2022. A Pump.fun link alone does not establish compatibility.'],
      ['Do I have to use World’s tokens or 500,000-token minimum?','No. Those are World-specific rules. Your developer chooses the supported mint, required quantity, duration and what the lock unlocks.'],
      ['Is the lock itself a retention guarantee?','No. A voluntary lock creates a participation window and a meme character can create a sense of belonging. Fun, progress and community activities give players reasons to return. The skill asks the developer to design and measure that loop; locked TVL alone is not retention.'],
      ['Can players get their tokens back?','Only after their chosen timelock expires. Current DevFridge docs describe a 2% redemption fee that buys and burns PASTA. Non-PASTA redemption requires an executable Jupiter route; the skill asks the developer to verify support and explain costs before locking.'],
      ['Will Phantom work on my phone?','The skill targets Phantom’s mobile in-app browser and desktop extension, with an explicit Open in Phantom fallback. Physical-device testing is still part of each game’s release process.'],
      ['Does the skill make scores impossible to cheat?','No. Token gating, wallet authentication and score verification solve different problems. Competitive games need server-authoritative sessions; even those cannot guarantee the absence of bots.'],
      ['Are all ecosystem components automatically included?','No. The core is Phantom plus DevFridge access. Other components are selected during discovery. Existing TopShelf, rewards or bridge systems require their own supported integration; the skill does not grant access to production services.'],
    ].map(([question,answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</section>
    <footer className={styles.footer}><a href="https://world.devfridge.cool/">DEVFRIDGE WORLD</a><span>Skill v1.5.0 · Sources reviewed 26 September 2026</span><div><a href="https://docs.devfridge.cool/sdk">SDK docs ↗</a><a href="/world/skill/downloads/manifest.json">Package checksums ↗</a><a href="https://connect.devfridge.cool/">Connect ↗</a></div></footer>
  </main>;
}
