import { CHAPTERS, SKILL_URL } from '@/lib/hackathon';
import CopyPrompt from './CopyPrompt';
import { SUBMISSION_PROMPT, SUBMISSION_INTRO, SUBMISSION_STEPS, SHOWCASE_STATUS } from '@/lib/game-builder-prompts';
import s from './hackathon.module.css';

export default function HackathonPage() {
  return <main id="main">
    <section className={s.hero}>
      <div className={s.heroText}><p className={s.eyebrow}><span className={s.dot} /> THE AGENTIC GAME-BUILDING HACKATHON</p><h1>Your meme.<br />Your <em>game.</em></h1><p className={s.lead}>Give your community a world to come back to.</p><p className={s.heroDescription}>Have a Pump.fun token—or an idea for one? Build a 3D browser game on Solana with your coding agent and the DevFridge stack. Desktop. Mobile. Phantom. Your rules.</p><div className={s.actions}><a className={s.primary} href="#start">Start with your agent <span>↗</span></a><a className={s.secondary} href="/hackathon/handbook/start">Read the handbook →</a></div><p className={s.micro}>Free skill & builder kit · No Git experience needed</p></div>
      <div className={s.heroArt} aria-label="Illustration: a community token becomes a playable world">
        <div className={s.artGrid} /><span className={s.artTag}>BUILD SOMETHING THEY CAN PLAY.</span>
        <div className={s.orbit}><div className={s.token}>YOUR<br /><strong>MEME</strong><small>SOLANA / TOKEN-2022</small></div></div>
        <div className={s.arcade}><div className={s.arcadeTop}><span>DEVFRIDGE / BUILDER</span><span>● ● ●</span></div><div className={s.screen}><div className={s.landscape}><i /><i /><i /></div><span className={s.player}>✦</span><span className={s.screenLabel}>A WORLD OF YOUR OWN</span></div><div className={s.console}><span>← ↑ ↓ →</span><b>PLAY ↗</b></div></div>
        <div className={s.codeTag}><span>&gt; community.lock()</span><span>&gt; game.unlock()</span><strong>&gt; let’s build_</strong></div><span className={s.artNote}>CONCEPT → CODE → PLAY</span>
      </div>
    </section>
    <div className={s.ribbon}><span>SOLANA</span><i>+</i><span>PUMP.FUN COMMUNITIES</span><i>+</i><span>THREE.JS</span><i>+</i><span>PHANTOM</span><i>+</i><span>YOUR CODING AGENT</span></div>
    <section className={s.section} id="start"><div className={s.sectionHead}><div><p className={s.eyebrow}>START HERE / NO BLANK PAGE</p><h2>Your first teammate<br />is your coding agent.</h2></div><p>Install the Game Builder skill. It asks about your idea, token and access rules, then guides the build with the actual DevFridge integration references.</p></div><CopyPrompt /><div className={s.belowPrompt}><a href={`${SKILL_URL}#quick-install`}>Explore the skill, examples & installation guide ↗</a><a href="#submit">Already have a game? Submit through your coding agent ↓</a></div></section>
    <section className={`${s.section} ${s.light}`} id="challenge"><div className={s.sectionHead}><div><p className={s.eyebrow}>THE CHALLENGE</p><h2>Make the meme<br />worth coming back for.</h2></div><p>Shared identity gets people through the door. A great game gives them a reason to stay. Timelocks turn a community token into a transparent access commitment.</p></div><div className={s.cards}>
      {[['01', 'Make it playable.', 'One complete loop. Clear controls, a satisfying result and a reason to hit play again. Arcade, puzzles, social worlds—pick your direction.'], ['02', 'Make it theirs.', 'Your community, your art direction, your compatible Solana mint. No need to reuse World’s characters or its token thresholds.'], ['03', 'Build on what works.', 'Reuse the DevFridge Solana timelock program through the SDK. Add Phantom, touch controls and a policy players can understand.']].map(([n,t,p]) => <article key={n}><span className={s.number}>{n}</span><h3>{t}</h3><p>{p}</p></article>)}
    </div><a className={s.textLink} href="/hackathon/handbook/timelocks">How timelocks work, why they help & what they cost →</a></section>
    <section className={s.section}><div className={s.sectionHead}><div><p className={s.eyebrow}>THE BUILD PATH</p><h2>Small steps.<br />A real game.</h2></div><p>The infrastructure already exists. Spend your creativity on the world, the mechanics and the community experience.</p></div><div className={s.steps}>{[['01','Brief your agent','Install the skill and define one strong gameplay loop.'],['02','Ship a prototype','Build your Three.js scene, controls, result and replay.'],['03','Connect the community','Verify Phantom and the exact DevFridge timelock policy.'],['04','Play it on a phone','Test touch, audio recovery, loading and wallet failures.'],['05','Submit through your agent','With the skill, your own coding agent prepares the evidence and opens the project PR for review.']].map(([n,t,p]) => <div key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></div>)}</div><div className={s.notice}><strong>Build it. Let your agent submit it.</strong><span>No Git experience needed: the skill prepares your project and opens its review request. Owner review, merge and deployment publish the gallery entry. Competition dates, judges and prizes remain to be announced.</span></div></section>
    <section className={s.section} id="submit"><div className={s.sectionHead}><div><p className={s.eyebrow}>YOUR CODING AGENT + THE DEVFRIDGE SKILL</p><h2>Submit through your agent.<br />No Git experience needed.</h2></div><p>{SUBMISSION_INTRO}</p></div><p className={s.submissionNote}>Copy this prompt into your own coding agent with the DevFridge Game Builder skill installed. Your agent submits the game; this website explains the process and displays the reviewed projects.</p><div className={`${s.steps} ${s.submissionSteps}`}>{SUBMISSION_STEPS.map(([number,title,text]) => <div key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></div>)}</div><CopyPrompt prompt={SUBMISSION_PROMPT} id="submission-prompt" label="Guided hackathon submission prompt" title="02 / YOUR AGENT → REVIEW → GALLERY" buttonLabel="Copy guided submission prompt"/><div className={s.belowPrompt}><a href="/projects">Explore the project gallery ↗</a><a href="/hackathon/handbook/submission">Read the submission guide →</a></div><div className={s.notice}><strong>Open for showcase submissions.</strong><span>{SHOWCASE_STATUS}</span></div></section>
    <section className={`${s.section} ${s.handbookSection}`} id="handbook"><div className={s.sectionHead}><div><p className={s.eyebrow}>THE BUILDER HANDBOOK</p><h2>Everything you need.<br />Nothing left vague.</h2></div><a className={s.secondary} href="/hackathon/kit/handbook.md" download>Download handbook ↓</a></div><div className={s.docGrid}>{CHAPTERS.map((c,i) => <a key={c.slug} href={`/hackathon/handbook/${c.slug}`}><span>0{i+1} / GUIDE</span><h3>{c.title} <b>↗</b></h3><p>{c.intro}</p></a>)}</div></section>
    <section className={s.section} id="kit"><div className={s.sectionHead}><div><p className={s.eyebrow}>PACK LIGHT. BUILD BIG.</p><h2>Your builder kit.</h2></div><p>Practical files for your agent, your repository and the people who will review your work.</p></div><div className={s.kitGrid}>{[['Skill + game examples', 'The recommended starting point for your agent.', SKILL_URL, 'INSTALL ↗'],['Submission template', 'Describe your game, mint, access policy and evidence.', '/hackathon/kit/submission.md','DOWNLOAD .MD ↓'],['AI build log', 'Record prompts, human review and tested outcomes.', '/hackathon/kit/build-log.md','DOWNLOAD .MD ↓'],['Review scorecard','Check your project against the 100-point rubric.','/hackathon/kit/scorecard.md','DOWNLOAD .MD ↓']].map(([t,p,url,cta]) => <a href={url} key={t} download={url.endsWith('.md') || undefined}><h3>{t}</h3><p>{p}</p><span>{cta}</span></a>)}</div></section>
    <section className={`${s.section} ${s.faq}`}><p className={s.eyebrow}>BEFORE YOU BUILD</p><h2>A few good questions.</h2>{CHAPTERS.find(c=>c.slug==='faq')!.sections.slice(0,6).map(q=><details key={q.title}><summary>{q.title}<span>+</span></summary><p>{q.paragraphs?.join(' ')}</p></details>)}<a className={s.textLink} href="/hackathon/handbook/faq">Read all questions →</a></section>
    <section className={s.finalCta}><p className={s.eyebrow}>THE NEXT WORLD COULD BE YOURS.</p><h2>Bring the meme.<br />Build the game.</h2><a className={s.darkButton} href="#start">Get the agent prompt ↗</a><a href={SKILL_URL}>Explore the DevFridge Game Builder skill →</a></section>
  </main>;
}
